### ISSUE TITLE
Secure Credentials Store Discussion

### ISSUE THREAD

**Issue by siepkes** [keycloak/keycloak-community#10]
@stianst I noticed the "Secure Credentials Store" writeup which looks like a good idea! I might have some insights for you to ponder on regarding the "Should everything be stored in a vault?" question.

If you project that question on Hashicorp Vault (so a specific Vault implementation) I don't think Vault meant to store that kind of domain data (domain data in the sense that it clearly belongs to Keycloak). Vault is mostly meant to store secrets which services themselves use. 

However Vault can actually help with storing such domain data securely via the [Transit Engine](https://www.vaultproject.io/docs/secrets/transit/index.html). Basically (as Vault puts it) it's "encryption as a service". So it allows you to store the data in your own database but the encryption and decryption is managed by Vault. Couple of advantages;

* You can't mess up the encryption implementation.
* The whole key management (enrollment, backup, unlocking, etc.) is already managed and provided by Vault. Especially if you already have a Vault infrastructure this makes your life a lot easier.

It might be an idea to make this plug-able in a way that people can for example use to provide a Vault transit engine implementation or perhaps a PostgrSQL implementation which uses native PostgreSQL database encryption or whatever people can come up with.

**Comment by stianst** [comment]
Thanks for this. I pretty much suspected this would be the case. We should probably go for encrypting the credentials into the database as the main solution, with potentially a way to obtain LDAP and SMTP credentials from a vault. From an implementation perspective that probably means two SPIs. One to read credentials from a vault and another to encrypt/decrypt credentials to store into the db. One complex thing with the latter is going to be to figure out how to re-encrypt everything in the db as part of key rotation.

**Comment by siepkes** [comment]
> From an implementation perspective that probably means two SPIs. 

That sounds like a good idea.

> One complex thing with the latter is going to be to figure out how to re-encrypt everything in the db as part of key rotation.

A standalone database implementation will indeed have a lot of problems like that one to solve (ie. a lot of wheel-reinventing).

For a Hashicorp Vault implementation most of that is actually already taken care of by Vault it self. For example see the [Transit Secrets Re-wrapping](https://learn.hashicorp.com/vault/encryption-as-a-service/eaas-transit-rewrap#encryption-key-rotation) documentation for key rotation.

Maybe it's an idea to first create the SPI infrastructure (interfaces and such) with a default implementation which does not actually encrypt anything. This is the same behavior as currently in Keycloak. However it will allow a Vault implementation to be made. Since Vault already tackles the complex issues you also identified so the implementation will probably be relatively easy. At least considerably more easy then writing a standalone implementation which has to tackle all these issues like key rotation, unlocking, etc. on it's own. 

Another thing that crossed my mind is (and I'm not really familiar with the low level internals of Keycloak so correct me if I'm wrong) is that these SPI's need to make calls over the network. Which means their interfaces should probably be treated as async (ie. return Futures, callbacks, reactive, etc.).

**Comment by stianst** [comment]
That would make a lot of sense. We add SecretStoreSPI and SecretEncryptSPI, then provide out of the box implementation for HashiCorp Vault only.

Quickly reading the transit secrets re-wrapping doc you mentioned it would probably be sufficient to re-encrypt slowly over time rather than everything at once. If the encryption keys are compromised a decision would have to be made whether or not the encrypted data was also compromised. If not it may be good to have an option to re-encrypt everything on demand, if it has been then all credentials are compromised and should be invalidated.

**Comment by stianst** [comment]
Realm keys should not be handled by the above SPIs, but rather we should handle it with separate key providers. We could also add a Vault realm key provider.

**Comment by stianst** [comment]
Closing this issue as the feedback has been taken into input in the new vault spi and the future coming encryption provider for secrets at rest
