### ISSUE TITLE
Create template easily

### ISSUE THREAD

**Issue by RemDav** [keycloak/keycloak-community#100]
Hello, I want to create a new template for all pages. However, I've been trying to create a simple page for several days. But I absolutely don't know the language to create a template. Is there a way to make html and translate it for keycloak?

**Comment by RemDav** [comment]
Or is it possible to create a webui that makes rest calls to keycloack? If yes, how? Because with Oauth2, you have to do redirection I think?

**Comment by stianst** [comment]
This is not a support forum - see https://www.keycloak.org/community for information on where to get help
