### ISSUE TITLE
Keycloak-gatekeeper has no admin interface

### ISSUE THREAD

**Issue by thomas-jakemeyn** [keycloak/keycloak-community#12]
# Context
We are securing a set of web applications with Keycloak and the Keycloak gatekeeper. The Keycloak gatekeeper is configured as a client of Keycloak.

# Problem
We get an error when using the Keycloak administration console to log out all active users. Keycloak properly removes the active sessions but fails to contact the [Admin URL](https://www.keycloak.org/docs/6.0/securing_apps/#admin-url-configuration) of the Keycloak gatekeeper client.

After some investigations, it looks like the Keycloak gatekeeper does not implement the `admin` endpoints.

- Is our assumption correct?
- Is there any solution / alternative?

**Comment by stianst** [comment]
The aim is to keep Gatekeeper as a generic OIDC proxy as such we do not want to add bespoke features like the admin endpoints. We should see if the OIDC backchannel logout specification would handle this use-case.

**Comment by stianst** [comment]
Closing this though as this is not the issue tracker for Keycloak projects, but rather specific to design proposals and other community related things. Please open a JIRA issue for your request instead.
