### ISSUE TITLE
Question: REST API  call to get access token of a user through admin username and password

### ISSUE THREAD

**Issue by ankkumar-progress** [keycloak/keycloak-community#155]
I have a requirement where I need to get an access token of a user.
I am aware of the admin username and password and hence can get the access token of the admin.
Is there any rest API that can provide me access token a user using the above data?

If it is not the correct repository to ask this question, can you please redirect it.

**Comment by stianst** [comment]
Hi, this is not the correct place to ask for help. Please see keycloak.org/community for details on how to ask for help.
