### ISSUE TITLE
Keycloak randomly returns 200 for GET /users/{id} API when 404 is expected

### ISSUE THREAD

**Issue by sadranishilpa** [keycloak/keycloak-community#156]
Hello All,
I am using keycloak 7.0.0 and I have setup multiple realms.
I am running a test that user admin of one realm<Realm1> should not be able to fetch users of other realm<Realm2> - 

Request URI - GET http://localhost:8080/auth/admin/realms/Realm1/users/userId
                          
I am expecting keycloak to return 404 but this behaviour seem to be random.
Keycloak sometimes return 404 that is user not found (as expected) but sometimes returns 200 with user details in response body.
If I manually check for this user in keycloak console Realm1 , the user is not present.
Has someone seen this issue before? Can someone guide me to resolve this issue.

Thanks

**Comment by stianst** [comment]
Please check keycloak.org/community to find out how to ask for help. This is not the right place.
