### ISSUE TITLE
Question - User attributes maps

### ISSUE THREAD

**Issue by carluis321** [keycloak/keycloak-community#158]
Hi! I'm still reading about Keycloak and learning a lot with this great tool, I'm using the last version of Keycloak and building a service that consumes Keycloak admin's API, when I create a User, I do it with the following data
`{
    "username": "user1",
    "firstName": "user",
    "lastName": "user",
    "email": "email2@gmail.com",
    "attributes": {
        "attr1": "value1"
    }
}`

And when I call the endpoint **http://localhost:5000/auth/admin/realms/{realm}/users?username=user1**

the answer that I recieve is
`[
    {
        "id": "e741b717-4aca-45e6-a10a-9705991f9806",
        "createdTimestamp": 1596059762402,
        "username": "user1",
        "enabled": false,
        "totp": false,
        "emailVerified": false,
        "firstName": "user",
        "lastName": "user",
        "email": "email2@gmail.com",
        "attributes": {
            "attr1": [
                "value1"
            ]
        },
        ...
    }
]`

with this answer the key "attributes" is an object that has a key and that key is an array, is this a normal behavior? 
Sorry if my English is not very good!

**Comment by stianst** [comment]
Hi, this isn't the correct place to ask for help or report issues. See https://www.keycloak.org/community for more details.
