### ISSUE TITLE
How to specify KeycloakHotRodMarshallerFactory when using 'hotrod-store' instead of 'remote-store'

### ISSUE THREAD

**Issue by tendaim** [keycloak/keycloak-community#159]
I'm using the hotrod-store in order for Keycloak (6.0.1) to communicate with an external infinispan cluster (9.4.18) over TLS. However, when I configure the 'marshaller' property on the hotrod-store to 'org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory' (see config snippet below), I see a the following warning in the Keycloak log: 
19:16:01,783 WARN  [org.infinispan.configuration.parsing.XmlConfigHelper] (MSC service thread 1-6) ISPN000292: Unrecognized attribute 'marshaller'. Please check your configuration. Ignoring!

hotrod-store config:
`                <replicated-cache name="work" remote-timeout="60000">
                    <hotrod-store remote-cache-container="clustered" cache-configuration="keycloak-cfg" fetch-state="false" passivation="false" preload="false" purge="false" shared="true">
                        <property name="marshaller">
                            org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory
                        </property>
                    </hotrod-store>
                </replicated-cache>`

Please let me know the correct way to set the marshaller for the hotrod-store.

Thanks,
Tendai

**Comment by stianst** [comment]
Hi, this isn't the correct place to ask for help or report issues. See https://www.keycloak.org/community for more details.
