### ISSUE TITLE
Question - How to map roles to permissions

### ISSUE THREAD

**Issue by priyanka-5** [keycloak/keycloak-community#160]
I have created realm, clients, roles for client and added users with specific role.
Now I want to create permissions to access resource and assign those permissions to roles. So that,I can use this data for authorization.
I am not using keycloak's authorization service. I have separate service for authorization. I am using keycloak for user management(authentication) only.
How can I assign permissions to roles so that my authorization service will use this data for policy eveluation? I explored keycloak's admin console and created resources and permissions but I don't see how can I map permissions to roles.

Thank you

**Comment by carluis321** [comment]
I am not one of the team of keycloak, but I think I can help you to do that, yo need to create a Permisson and add policies to that permission, there is a Role-based access control, you need to specify the needed roles to apply that permission

**Comment by priyanka-5** [comment]
@carluis321 thank . But my question is if we add policies for permission, keycloak will be used as authorization service. Bu I don't want keycloak's authorization service. I have my own authorization service. I just want to bind permissions to roles using keycloak. My authorization service have policies defined in it.

**Comment by stianst** [comment]
Hi, this isn't the correct place to ask for help or report issues. See https://www.keycloak.org/community for more details.
