### ISSUE TITLE
jboss/keycloak is not working with mysql database.

### ISSUE THREAD

**Issue by priyanka-5** [keycloak/keycloak-community#162]
I am running keycloak with docker. I have used jboss/keycloak docker image. I am using mysql database which is also running in docker container. But with mysql DB keycloak service is not getting started. Its working fine with postgres. Also its working with mysql DB on Windows but not on ubuntu 18.04.

**Comment by stianst** [comment]
Hi, this isn't the correct place to ask for help or report issues. See https://www.keycloak.org/community for more details.
