### ISSUE TITLE
realm-management cannot do any action via postman !!

### ISSUE THREAD

**Issue by RRadziejewski** [keycloak/keycloak-community#166]
Hi,

I am running keycloak in dockerfile jboss/keycloak:6.0.1  but this applies also to latest version and 9.0.0 for sure.
When trying to get some info with **realm-management** client i get 403 all the time for example on listing users with url:

http://xxxxxxxx/:8580/auth/admin/realms/x-x/users

I get the token with client-id and secret this works but later i cannot do any request on the api.

Service Accounts Enabled
Valid Redirect URIs *
Web origins *

Roles list:

- view-clients
- manage-events 
- manage-users
- query-users 
- create-client
- view-users
- impersonation 
- view-realm
- manage-realm
- manage-clients
- query-realms
- view-events
- query-clients
- view-authorization
- uma_protection 
- view-identity-providers
- manage-identity-providers
- realm-admin 
- query-groups
- manage-authorization

Anybody seen this kind of an issue ? What can i do , check to solve the issue? Please help

**Comment by stianst** [comment]
Hi, this isn't the correct place to ask for help. Take a look at keycloak.org/community for more info
