### ISSUE TITLE
JWKS endpoint contains certificate but not publickey?

### ISSUE THREAD

**Issue by asyncify** [keycloak/keycloak-community#168]
I'm trying to programmatically verify tokens issued by a Keycloak AS. In order to do that, I understand that I need to retrieve the publickey which signed the tokens, and thought I could get that from the Keycloak JWKS endpoint (http://<keycloak>/auth/realms/<realm>/protocol/openid-connect/certs).

But the JSON object returned does not contain the publickey, it contains the server certificate, which on my Keycloak are different. Is that expected? How should I be verifying a token signature, if not from the publickey?

Thanks.

**Comment by stianst** [comment]
Please see https://www.keycloak.org/community for details on how to ask for help
