### ISSUE TITLE
JWT client authentication fails using kubernetes service account tokens

### ISSUE THREAD

**Issue by janssk1** [keycloak/keycloak-community#180]
I'm trying to use kubernetes generated (bound) service account tokens to authenticate my client against keycloak. 

However, keycloak requires the token to have a jti, while the tokens generated by kubernetes don't have that. Seems the jti requirement got introduced while adding replay protection: https://github.com/keycloak/keycloak/commit/1b5a83c4f1abfdc79189c342ca2dcd1b646c2522

Now, one can argue that its more secure to require a jti, but on the other hand it breaks some integration (jti is optional in the JWT spec). 

Any chance of (conditionally) dropping this jti requirement ? 
Alternatives I have is creating my own custom token authenticator (which i want to prevent) or get a fix in KS. 

For reference, these are the token contents of a bound service account token generated by kubernetes:

{  "aud": [    "myAudience"  ],  "exp": 1600977298,  "iat": 1600973698,  "iss": "kubernetes.performance.svc",  "kubernetes.io": {    "namespace": "janssk1",    "pod": {      "name": "source-ip-app-74bf7f6fc8-clw9s",      "uid": "f6156f01-fa6d-4605-9584-f1af42e88b08"    },    "serviceaccount": {      "name": "default",      "uid": "cb3fdf02-218a-4093-b66a-0ea032e09113"    }  },  "nbf": 1600973698,  "sub": "system:serviceaccount:janssk1:default"}
--

**Comment by stianst** [comment]
Please see https://www.keycloak.org/community
