### ISSUE TITLE
Import realm from json file

### ISSUE THREAD

**Issue by zakariae-lebriq** [keycloak/keycloak-community#184]
Hi guys, 

I'm trying to import a realm from JSON exported file, but it doesn't work as expected. Let me give you more details to make this story clearer. I have created some custom configurable authenticators and configured them before I exported the JSON file. However,  the configuration of those authenticators is never imported and it's always empty. Therefore, I have to do it by myself each time I import a realm.

Does anyone of you guys have some brilliant ideas about how to solve this problem? 

I still not sure whether keycloak has the ability to handle the configuration of custom authenticators and that I can achieve my aim.

Thanks a lot

**Comment by hmlnarik** [comment]
Please use [keycloak-user mailing list](https://www.keycloak.org/community) for this type of questions.
