### ISSUE TITLE
Invalid parameter: redirect_uri between jupyterhub and keycloak

### ISSUE THREAD

**Issue by Freir96** [keycloak/keycloak-community#185]
I have set up my jupyterhub working on Vagrant to use keycloak authorization, but I keep getting this error:

> We are sorry... Invalid parameter: redirect_uri

And this is the log from keyclock server:

> 2020-10-29 10:34:58,025 WARN  [org.keycloak.events] (default task-5) type=LOGIN_ERROR, realmId=master, clientId=account, userId=null, ipAddress=10.0.2.2, error=invalid_redirect_uri, redirect_uri=http://192.168.100.1:8600/hub/oauth_callback

jupyterhub_config.py:

`
host_ip = '192.168.100.1'
ip = host_ip
keycloak_guest_port = '8180'
keycloak_host_port = '8586'
keycloak_port = keycloak_host_port
c.JupyterHub.authenticator_class = GenericOAuthenticator

c.OAuthenticator.client_id = 'account' 

c.OAuthenticator.client_secret = '5110687d-5c91-406d-8721-2f09b11e21fe' 

c.GenericOAuthenticator.token_url = "http://" + ip + ":" +keycloak_port + "/auth/realms/master/protocol/openid-connect/token" 

c.GenericOAuthenticator.userdata_url = "http://" + ip + ":" +keycloak_port + "/auth/realms/master/protocol/openid-connect/userinfo" 

c.GenericOAuthenticator.userdata_method = 'GET'

c.GenericOAuthenticator.userdata_params = {'state': 'state'}

c.GenericOAuthenticator.username_key = 'admin' 
`

Enviromental variables:

`
export OAUTH2_TOKEN_URL=http://192.168.100.1:8586/auth/realms/master/protocol/openid-connect/token
export OAUTH2_AUTHORIZE_URL=http://192.168.100.1:8586/auth/realms/master/protocol/openid-connect/auth
export OAUTH_CALLBACK_URL=http://192.168.100.1:8600/hub/oauth_callback
`

Ports:
`
config.vm.network "forwarded_port", guest: 8000, host: 8600

config.vm.network "forwarded_port", guest: 8001, host: 8601

config.vm.network "forwarded_port", guest: 8081, host: 8681

config.vm.network "forwarded_port", guest: 8180, host: 8586
`
My keycloak installation:
`
cd $KEYCLOAK_PATH/bin && sudo bash add-user-keycloak.sh -u admin -p admin
cd $KEYCLOAK_PATH/bin && sudo nohup ./standalone.sh -Djboss.bind.address.management=0.0.0.0 -Djboss.socket.binding.port-offset=100 -Djboss.bind.address=0.0.0.0 > $KEYCLOAK_LOGS/keycloak.log 2>&1 &

`

Nothing I've found helped me solve this issue. All the url's are exactly my keycloak endpoints.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
