### ISSUE TITLE
Get a role by name endpoint returning 404

### ISSUE THREAD

**Issue by rosariop** [keycloak/keycloak-community#186]
according to the following rest api template i should get a list of all my clients roles:
`GET /{realm}/clients/{id}/roles`
when hitting the endpoint `localhost:8081/drivingschool/clients/24b3ecaf-8885-4b88-a473-1011518c3c90/roles`
it's returning a http 404.

I've got following three questions:
1) why is {realm} the realms name but {id} the id of the client and not the client-id
2) where do I find the clients id except in the URL of my keycloak
3) why is it returning a http 404 when hitting on the endpoint
`localhost:8081/drivingschool/clients/24b3ecaf-8885-4b88-a473-1011518c3c90/roles`

3.1
![grafik](https://user-images.githubusercontent.com/30045990/97789440-c94efd80-1bc0-11eb-98fc-73b891761244.png)

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
