### ISSUE TITLE
Register node at startup - cannot authenticate client

### ISSUE THREAD

**Issue by ltorzynski** [keycloak/keycloak-community#187]
Hi,

Keycloak version 11.0.1.
Functionallity desribed here: https://www.keycloak.org/docs/latest/securing_apps/#_registration_app_nodes does not work.

Cannot register node in keycloak, because keycloak cannot authenticate client, although valid registration request is posted to url: /auth/realms/{realm-name}/clients-managements/register-node

The problem is that context.getHttpRequest().getDecodedFormParameters() invocation in keycloak in every concrete implementation of: AbstractClientAuthenticator returns empty map, instead of valid post parameters.
I suppose that its because ealier resteasy method:
MessageBodyParameterInjector.inject method processes the request, reading whole input stream prior to invoking getDecodedFormParameters() method at least once.
How to successfully authenticate client in this case ?

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
