### ISSUE TITLE
realm-admin role user able to view "Server Info"

### ISSUE THREAD

**Issue by harishjadhav26** [keycloak/keycloak-community#189]
I have created user and set realm-admin role to this user and after login click on user info then "Server Info" tab is able to view 
Shall we restrict this tab to publish end users.

![image](https://user-images.githubusercontent.com/57670076/98803215-69ffb180-243a-11eb-9238-14de64b5919c.png)

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
