### ISSUE TITLE
Theming client's account, admin console and email

### ISSUE THREAD

**Issue by akos96kov** [keycloak/keycloak-community#192]
Hello!

Is there any way to set **account, admin console and email** themes for **clients**? I think this feautre only available for **realms**:

![realm_theme](https://user-images.githubusercontent.com/58334547/99092605-a6b1e100-25d1-11eb-90e3-e5c6a98cfd81.JPG)

But I would like to set separately for clients (like login theme for client):

![Képkivágás](https://user-images.githubusercontent.com/58334547/99105589-141a3d80-25e3-11eb-8ae8-6b96cc23f4ab.JPG)

Keycloak version: 10.0.2

Thanks for the answers!

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
