### ISSUE TITLE
Keycloak Auth cookies with secure flag

### ISSUE THREAD

**Issue by kaabar** [keycloak/keycloak-community#196]
Hi,

Keycloak relies on the realm setting "Require SSL" to decide whether to set the secure flag to its session cookies or not. When the value is set to "external calls" and keycloak is behind a reverse proxy which perform SSL termination, the secure flag is not set to true in the cookies.
Keycloak should check if the actual made to to the reverse proxy it https and that the call is coming through a reverse proxy or not.

P.S: I cannot set the value to "all requests" since i have other plain http requests coming from inside the cluster.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
