### ISSUE TITLE
Blank in realm name breaks refresh of expired token

### ISSUE THREAD

**Issue by itconomic-ralph** [keycloak/keycloak-community#197]
A blank in the KeyCloak realm name leads to the method refreshExpiredToken() in RefreshableKeycloakSecurityContext to always return false because of the following:
```
if (!this.getRealm().equals(this.deployment.getRealm())) {
            // this should not happen, but let's check it anyway
            return false;
 }
```
In case the realm name contains a blank, it is still URL-encoded in this.deployment.getRealm() but not in this.getRealm(). Therefore the equals compares " " with "%20" which is false.

**Comment by itconomic-ralph** [comment]
Maybe the realm field in KeyCloak web interface should prevent users from usiing blanks in the realm name.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
