### ISSUE TITLE
UserStorageManager inconsistent behaviour on getUsersCount

### ISSUE THREAD

**Issue by drobert-bfm** [keycloak/keycloak-community#198]
In version 11.0.2:

org.keycloak.storage.UserStorageManager.getUsersCount overloads have inconsistent implementations that violate expectations:

public int getUsersCount(RealmModel realm, boolean includeServiceAccount):
public int getUsersCount(RealmModel realm) :
  these goes through all the enabled UserQueryProvider implementations and sums the counts for all providers.

public int getUsersCount(RealmModel realm, Set<String> groupIds):
public int getUsersCount(String search, RealmModel realm):
public int getUsersCount(String search, RealmModel realm, Set<String> groupIds):
public int getUsersCount(Map<String, String> params, RealmModel realm):
public int getUsersCount(Map<String, String> params, RealmModel realm, Set<String> groupIds):
  these only count users in localStorage()

This leads to REST calls to /users/count where if there is, for example, a "search=x" parameter passed, only the count for localStorage() is returned, but if there isn't a parameter, the count across all valid providers is returned. 

All getUsersCount() overrides should instead support all enabled UserQueryProvider instances, since the interface defines methods to support all those variants.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
