### ISSUE TITLE
keycloak json logs

### ISSUE THREAD

**Issue by vukomir** [keycloak/keycloak-community#20]
Hi,

i'm tried to enable json log form on keycloak server docker image using custom scripts cli but it dose not work

```embed-server --server-config=standalone.xml
batch
/subsystem=logging/json-formatter=json:add(exception-output-type=formatted, pretty-print=false, meta-data={label=value})
/subsystem=logging/console-handler=CONSOLE:write-attribute(name=named-formatter, value=json)

# Execute and reload
run-batch
stop-embedded-server
```

i also tried the same script and deleting tu build docker image by executing the same script and deleting 
/opt/jboss/keycloak/standalone/configuration/standalone_xml_history

same result 

did anyone manage to enable json log format ?

Vuko

**Comment by stianst** [comment]
Hi, this is the place to report issues/discussions around design proposals, not general help around Keycloak and feature requests. Please open a thread on the user mailing list or a JIRA feature request. Right now we have not tested JSON logging or documented how to enable it ourselves, however it should work as it should be enabled by WildFly.
