### ISSUE TITLE
User Event SPI

### ISSUE THREAD

**Issue by magick93** [keycloak/keycloak-community#205]
Hi @vmuzikar 

The [User Event SPI](https://github.com/keycloak/keycloak-community/blob/master/design/user-event-spi.md) sounds really interesting - and very useful!

Do you know if this proposal is going ahead?

**Comment by vmuzikar** [comment]
@magick93 Thank you for your interest in the SPI!
Although there wasn't much progress recently as it is waiting for some reviews (https://github.com/keycloak/keycloak/pull/7466), you can track the progress [here](https://issues.redhat.com/browse/KEYCLOAK-15449).

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
