### ISSUE TITLE
Keycloak User are not showing

### ISSUE THREAD

**Issue by babanjot** [keycloak/keycloak-community#206]
In my keycloak users are not showing
When I click on View all user 
![image](https://user-images.githubusercontent.com/60752411/103088420-c4328b80-4610-11eb-9c11-d2a5ac1f5f6d.png)
It doesn't reflect anything.

Any help will be appreciable.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
