### ISSUE TITLE
OIDC redirect uri not well formed when using fragment response_mode

### ISSUE THREAD

**Issue by albinscode** [keycloak/keycloak-community#208]
Hello, 

# Testing environment

I've come into an issue by setting up the following environment:

* an Angular application (SPA) with hash location strategy (home page is http://address/#/index.html
* OAuth2 OIDC setup with code workflow (PKCE)
* a keycloak server using official dockhub image version 12.0.0

# Problem

Here are the steps:

1. I'm accessing the SPA without being authenticated
2. I'm redirected to keycloak
3. I enter the the credentials on the login page
4. I'm redirected to the following url (for example) with the code provided by keycloak which leads to infinite loops between SPA and keycloak:

~~~
http://address:4200/#/index.html&state=c192UVdicXUtYWh5S2Uycm9mMGJJMVhrWklMMlRxbXpBaGtWdWFScV8yZHhS&session_state=ade3186c-ac42-4dde-bd3d-81647c111e46&code=b1797d8f-1df7-4cb3-998a-13c9fc1c11d8.ade3186c-ac42-4dde-bd3d-81647c111e46.5bb0202f-9a1a-4dc2-a709-3c86cec83717
~~~

# Quick explanation

The keycloak provided url is not well formed, the `state` parameter is appended directly with an ampersand instead of a question mark.
The SPA doesn't detect passed parameters, so no code retrieved and it tries to authenticate several times.

As a workaround, I've provided in my configuration of the SPA a redirect uri with a first fake argument like this: `http://address:4200/#/index.html?fake=fake`.

This way, all parameters are appended to build a valid url like this for example:
~~~
http://address:4200/#/index.html?fake=fake&state=c192UVdicXUtYWh5S2Uycm9mMGJJMVhrWklMMlRxbXpBaGtWdWFScV8yZHhS&session_state=ade3186c-ac42-4dde-bd3d-81647c111e46&code=b1797d8f-1df7-4cb3-998a-13c9fc1c11d8.ade3186c-ac42-4dde-bd3d-81647c111e46.5bb0202f-9a1a-4dc2-a709-3c86cec83717
~~~

# Question

Is there a parameter I'm missing in the keycloak configuration or is it a real bug?

Thank you by advance.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
