### ISSUE TITLE
Realm security-admin-console erro 404

### ISSUE THREAD

**Issue by andreisilvasantos** [keycloak/keycloak-community#211]
We set up a new Keycloak server with version 12.0.1. When creating a new clean Realm, the security-admin-console client page displays the error in the image below.

![image](https://user-images.githubusercontent.com/28400202/104062395-2a0a4000-51d9-11eb-9028-14ea2c4b4ee7.png)

Apparently the application is requesting some resource not found. The HOST / auth / admin / test / console / url is correct. It was generated by Keycloak himself. When we click on the link it loads the page correctly. When analyzing network traffic in the browser, an error 404 is shown for a route of realms resources.

![image](https://user-images.githubusercontent.com/28400202/104093743-4951ad80-526b-11eb-8301-31a27ce16071.png)

I realized that the cause of the error is that I did not assign the user the role of viewing or managing realms on the client.

![image](https://user-images.githubusercontent.com/28400202/104093721-13acc480-526b-11eb-88fd-a81343f7ae1f.png)

This is the standard that I used in version 11 of Keycloak so that account management users had the view only of users and groups.

![image](https://user-images.githubusercontent.com/28400202/104093762-66867c00-526b-11eb-8f89-9d752f89a2af.png)

**Would there be a way to not assign this privilege and avoid error 404?**

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
