### ISSUE TITLE
llegalStateException: Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Both Please select just one

### ISSUE THREAD

**Issue by a943915349** [keycloak/keycloak-community#212]
In springboot2.4. X, if enable "@ EnableWebSecurity", will have the following error "llegalStateException: Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Both Please select just one."

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
