### ISSUE TITLE
[Bug] TFA not working with Password Resets

### ISSUE THREAD

**Issue by sbazzell** [keycloak/keycloak-community#214]
If a user already has TFA configured, when initiating a "forgot password" password reset, keycloak will till tell them they need to register TFA in order to do so.  This just makes a duplicate and makes a mess of things.

What I would like is for TFA to ONLY be used for password resets, and not every time you log in.  Is this possible?

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
