### ISSUE TITLE
Usage of MULTIVALUED_LIST_TYPE for Authentication Flows

### ISSUE THREAD

**Issue by jonasvoelcker** [keycloak/keycloak-community#217]
Hey there,

as we are progressing to use your awesome platform, we dive deeper into unknown territory. We had the idea to use the ProviderConfigProperty.MULTIVALUED_LIST_TYPE within our Authentication Flows but encountered a missing declaration inside the FTL.

https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/admin/resources/templates/kc-component-config.html
https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/admin/resources/templates/kc-provider-config.html

The kc-component-config above contains a snippet for the MultivaluedList whereas the kc-provider-config doesn't. Did you leave this out because it doesn't work or didn't you try yet?

I am willing to support with a pull request, but will not be able to clarify it being working correctly. Additionally I don't know, which Unit-Tests might have to change.

Best Regards
Jonas

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
