### ISSUE TITLE
UserLookupProvider: getUsersByEmail

### ISSUE THREAD

**Issue by jonasvoelcker** [keycloak/keycloak-community#218]
Hi there,

our Keycloak doesn't use unique Email-Adresses but we are forced to offer a custom search by Email to our services.

Currently we use getUserByEmail out of UserLookupProvider for that, but it does not allow multiple return values.

We've set the realm.isDuplicateEmailsAllowed() flag so there will be multiple accounts per email, unfortunately there is no way to get multiple accounts through the UserLookupProvider.

I can't measure the impact for a new method List<UserModel> getUsersByEmail. But for the JpaUserProvider it will be a quick win as there is currently a list being returned and the ensureEmailConstraint method just needs to be left out.

Through the existence of isDuplicateEmailsAllowed it might be a major benefit for the product, please consider to offer it ;)

Best Regards
Jonas

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
