### ISSUE TITLE
404 in admin console after reanming

### ISSUE THREAD

**Issue by belfhi** [keycloak/keycloak-community#219]
Hello,
I have an issue with Keycloak where switching to a Realm 
gives me a 404 error,
```
Failed to load resource: the server responded with a status of 404 () /auth/admin/realms/OldRealmName/localization/en:
```
I renamed Realm and everywhere else in Keycloak the new name is used 
except for when I use the top left menu to quickly switch between realms.
Does anyone have an idea? This wasn't an issue with Keycloak 11

**Comment by Hounddog** [comment]
We are affected by the same issue as the localization is refering to the Realm ID instead of the realm name

**Comment by belfhi** [comment]
Ah, I didn't know that was the case. Have you found where that could be happening in the code? Changing the reference to the realm name instead should be easy enough...

**Comment by ginkel** [comment]
I am also seeing this issue. Is there a way to consistently change the real ID to the new name on the database?

**Comment by belfhi** [comment]
yes, it's already been fixed in the master.
You can use the official image and do the following to fix it

```
FROM jboss/keycloak:12.0.2

RUN /bin/sed -i '107s/currentRealm/Current\.realm\.realm/g'  /opt/jboss/keycloak/themes/base/admin/resources/js/controllers/realm.js
```
hope that helps

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
