### ISSUE TITLE
How are the scopes mapped for a client 

### ISSUE THREAD

**Issue by aarti-stack** [keycloak/keycloak-community#22]
I am  using Keycloak as a access manager  for the client Spring Cloud Data Flow .I have integrated with Open LDAP through User Federation for the users and have mapped LDAP groups as roles in the Keycloak.

All these scopes are mapped as groups in Open LDAP and I have created a role-ldap-mapper for it.Below are the list of roles

Scope dataflow.create maps to the CREATE role

Scope dataflow.deploy maps to the DEPLOY role

Scope dataflow.destroy maps to the DESTROY role

Scope dataflow.manage maps to the MANAGE role

Scope dataflow.modify maps to the MODIFY role

Scope dataflow.schedule maps to the SCHEDULE role

Scope dataflow.view maps to the VIEW role

I am able to authenticate the user but I get Roles missing error  while I land on the Spring cloud data flow dashboard page.

**Comment by stianst** [comment]
Hi, GitHub issues are are exclusively to discuss design proposals for new features. For help please use our user mailing list. Check out keycloak.org/community for details
