### ISSUE TITLE
AUTH_SESSION_ID cookie always secure

### ISSUE THREAD

**Issue by nikoregister** [keycloak/keycloak-community#220]
AUTH_SESSION_ID has always attribute secure. 

In source code keycloak-services-12.0.1

In authentication session manager there is secure property setted by realm configuration.

```
AuthenticationSessionManager.setAuthSessionCookie
...
boolean sslRequired = realm.getSslRequired().isRequired(session.getContext().getConnection());
...
        CookieHelper.addCookie(AUTH_SESSION_ID, encodedAuthSessionId, cookiePath, null, null, -1, **sslRequired**, true, **SameSiteAttributeValue.NONE**);
```

But in CookieHelper.addCookie there is

```
        boolean secure_sameSite = sameSite == **SameSiteAttributeValue.NONE** || secure; // when SameSite=None, Secure attribute must be set
...
        ServerCookie.appendCookieValue(cookieBuf, 1, name, value, path, domain, comment, maxAge, secure_sameSite, httpOnly, sameSite);
```

so AUTH_SESSION_ID is always secure. 

Because of this behavior, the following scenario is not working. 

**Keycloak configuration**
Keycloak running on http(development environment), realm frontend url http://mykeycloak.test/auth
Realm require ssl: None
Configured SAML 2.0 IdP
Configured client, using OIDC

**Flow**
User logs to the application by Keycloak mapped SAML IdP.
User's application ask for Refreshing External Tokens by re-initiating the account linking API.
Everything works fine while user has valid (browser) session in IdP and login is processed automatically.
But when user's session is ended in IdP, the login proces in IdP goes through login/password page and after succesful login is redirected back to keycloak and keycloak ends with error.

21:15:28,836 WARN  [org.keycloak.events] (default task-64) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=ISOH, clientId=null, userId=null, ipAddress=127.0.0.1, error=invalid_code

And the following error message "invalidCodeMessage" is shown to the user.

With the only one change - changing the frontend url from http to https everything works fine, but for some environments we need only http.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
