### ISSUE TITLE
Keycloak.X 12.0.2 behind reverse proxy: account management not accessible 

### ISSUE THREAD

**Issue by michael4screen** [keycloak/keycloak-community#222]
### Context

We have a Keycloak.X running inside a kubernetes cluster that is accessible from outside the cluster via a reverse proxy.
The reverse proxy is configured to map incoming requests on **/auth** to **/** on the keycloak container. 
We have following configuration:
 
- Proxy Mode: edge
- hostname-admin-url=https://example.com/auth
- hostname-frontend-url=https://example.com/auth

### Process

When clicking on _Manage Account_ within the administration UI. 

### Expected result

The hostname URL configuration is taken into account and thus the Manage Account UI is opened at path:  **/auth/realms/master/account/**

### Current result

The URL that is opened is **/realms/master/account/**, which leads to a 404, as the reverse proxy listens beneath **/auth**.

Are we missing some url configuration here or is this a bug ?

Best regards, 

Michael

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
