### ISSUE TITLE
Missing id_token_hint on external logout

### ISSUE THREAD

**Issue by bob-sheknowdas** [keycloak/keycloak-community#223]
I have an OIDC-IDP behind my Keycloak.

When a user logs in and than immediately logs out again, keycloak sends an id_token_hint.
However if the user stays logged in for more than 20 min no id_token_hint is passed (and the external logout fails).

20 min is the lifetime of the external access token. But I dont see why that should matter for an id_token_hint.

The ID token is a JWT with iat and exp parameters that define a lifetime of 12 hours.

I have the "store tokens" and "store tokens readable" options set to TRUE in my idp settings within keycloak.

I checked the code, but couldn`t find out, what is causing my issue (https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L235)

I have tried keycloak version 11.0.2 as well as the most current 12.0.2

Is there any way for me to make keycloak send an id_token_hint at least as long as the id token is valid?

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
