### ISSUE TITLE
Keycloak - can't  request a token with a custom lifespan?

### ISSUE THREAD

**Issue by wattariBat** [keycloak/keycloak-community#226]
Using KeyCloak to secure our Application we want to use Token acces for the APIs we have. like Github Api Token or Jira with long LifeSpan , I can change the default lifespan using the Admin API, but I want to keep this default lifespan for most tokens for the normal authent on the application . However, I want the capability to specify a different lifespan when requesting specific tokens (For API).

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
