### ISSUE TITLE
Token_exchange guidelines fail

### ISSUE THREAD

**Issue by jas1989** [keycloak/keycloak-community#228]
Hi, 
i'm trying to exchange a token from FusionAuth to Keycloak but I was unable to do that.
Thus I tried an easier case, namely to exchange token between two clients in keycloak existing in the same realm.
I follow the [documentation](https://www.keycloak.org/docs/latest/securing_apps/#_token-exchange) and this is the procedure i followed.
- run on docker (quay.io/keycloak/keycloak:12.0.2)
- enable token_exchange permission (-Dkeycloak.profile=preview)
- create 2 clients with "access_type" = confidential (starting_client and target_client)
- set policy for target_client relating to starting_client
- we get a valid token for starting_client calling the login endpoint
- make POST request like the following image
![image](https://user-images.githubusercontent.com/25514850/106788801-baf5ff00-6651-11eb-8ff0-ff7695f79e3b.png)

However I keep having an internal error:
![image](https://user-images.githubusercontent.com/25514850/106788927-e4168f80-6651-11eb-81d8-83d08f67787a.png)

Can anyone help me to solve this?
Thanks in advance

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
