### ISSUE TITLE
Add identity provider SAML2 entityID input field MISSING within the SAML Config Panel 

### ISSUE THREAD

**Issue by gencube** [keycloak/keycloak-community#230]
Hi Developer,

We are tasked to integrate with an SAML IdP .
https://www.keycloak.org/docs/latest/server_admin/#saml-v2-0-identity-providers
From the documentation above there is a mentioned

"Service Provider Entity ID | This is a required field and specifies the SAML Entity ID that the remote Identity Provider will use to identify requests coming from this Service Provider. By default it is set to the realm base URL /auth/realms/{realm-name}."

However we cannot find the input field in the online form where this is suppose to be inputted.

We have also tried to import IdpSamlMetadata.xml but the server reported there is error or missing field in
the XML file. We have checked the XML, there seems to be no error. All the core fields are available in the XML.

Is there a working XML sample we can see and modify accordingly?

Our KeyCloak server is version 11.0.2 Community Edition.

Kindly please assist as the project deadline is near.
We do not mind to do a private zoom stream in session at your best available time to show all the needed steps we done.
Thanks very much.

email: mattongbp@gmail.com

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
