### ISSUE TITLE
A functional Sample Restful POST for Create a new SAML identity provider

### ISSUE THREAD

**Issue by gencube** [keycloak/keycloak-community#231]
Hi Developer,

Can someone please help to provide a sample curl Restful POST call to create a SAML 2 Identity Provider?
We wish to integrate with a know public SAML 2 provider from our client
https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_identityproviderrepresentation
Create a new identity provider
POST /{realm}/identity-provider/instances

IdentityProviderRepresentation
config (optional) | Map

There is no such detail document found anywhere.
Our deadline for project is near.  Please help.

This is related to this issue:
https://github.com/keycloak/keycloak-community/issues/230

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
