### ISSUE TITLE
How to exclude a webpage (or whole folder) from being secured from keycloak

### ISSUE THREAD

**Issue by JonCSgr** [keycloak/keycloak-community#234]
I am really new to keycloak. I have a maven java servlet web application running on tomcat. I installed the tomcat dependencies needed and did all the required configurations according to the tutorial at keycloak both on my realm and my web application.

My issue is that keycloak secured all my webpages and i am getting HTTP Status 403 – Forbidden unless logged in even on my main page.

How can i exclude a webpage from keycloak ? I want that page accessible to anyone since it’s my main page where users can view a log in button.

![image](https://user-images.githubusercontent.com/61245954/107207450-fc4b2d80-6a08-11eb-8d2a-31cac2a6a0f7.png)

**Comment by JonCSgr** [comment]
Question :
if i dont put the adapter on tomcat but put it on the servlet application that would work best for my problem right?

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
