### ISSUE TITLE
ASP.NET MVC 4.7.2 OpenId connect claim token/values null

### ISSUE THREAD

**Issue by mohanrajcognizant** [keycloak/keycloak-community#235]
I have used ASP.NET MVC 4.7.2 OpenId connect OWIN with Keycloak tool . Authenticating successful however unable to get the ClaimsPrincipal like suject , username, given name, tokens. is any missing to  enable in keycloak tool.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
