### ISSUE TITLE
problem with logout and uri redirect

### ISSUE THREAD

**Issue by jbrongtr** [keycloak/keycloak-community#236]
## Sumamry
The website we built, upon logout, will send a call to the `/auth/realms/{realm}/protocol/openid-connect/logout` endpoint and tack on the `post_logout_redirect_uri`.

For this issue we'll consider 2 types of logouts:
- a logout by pressing a button
- a logout due to timeout

## Issue

When using the button to logout, it seems that 100% of the time we get the correct response and redirected to our correct destination.

When testing timeout, we intermittently receive back a 500 response from keycloak. In the logs we see:
```java
18:07:16,539 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-678) Uncaught server error: java.lang.IllegalStateException: Can't add session: task in progress for session
```
We are not properly redirected to the correct destintation.

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
