### ISSUE TITLE
Keycloak.X 12.0.2 custom scripts are not loaded

### ISSUE THREAD

**Issue by michael4screen** [keycloak/keycloak-community#237]
### Context

I'm trying to use script mappers on Keycloak.X 12.0.2 . 
I started from [this](https://www.keycloak.org/docs/latest/server_admin/index.html#script-mapper)
Then I read up on how to setup a simple Javascript provider [here](https://www.keycloak.org/docs/latest/server_development/#_script_providers)
And read on how to use custom providers on KeycloakX [here](https://github.com/keycloak/keycloak-containers/tree/master/server-x#extending-the-image) 

I built a jar file my-keycloak-scripts.jar:

```
META-INF/MANIFEST.MF
META-INF/keycloak-scripts.json
my-mapper.js
```
keycloak-scripts.json:

```
{
  "authenticators": [
  ],
  "policies": [
  ],
  "mappers": [
    {
      "name": "My mapper",
      "fileName": "my-mapper.js",
      "description": "Map apples into the token"
    }
  ]
}
```
my-mapper.js:

`token.setOtherClaims(“random_thing”,“apple”);`

Then i build my docker file, where i inject the scripts and **enable the scripts feature**:

```
FROM quay.io/keycloak/keycloak-x:12.0.2

COPY /my-keycloak-scripts.jar /opt/jboss/keycloak/providers/my-keycloak-scripts.jar

WORKDIR /opt/jboss/keycloak

RUN ./bin/kc.sh config --features-scripts=enabled --db=postgres
```

When booting the server i can see a log statement:

`keycloakx_1  | 2021-02-13 08:54:43,565 INFO  [org.key.com.Profile] (main) Preview feature enabled: scripts
`
and i can verify that my jar is available at `/opt/jboss/keycloak/providers/my-keycloak-scripts.jar`

**Expected result**

I would expect my mapper to be selectable in the admin UI. 

**Actual result**

The mapper is not accessible.

![image](https://user-images.githubusercontent.com/76940633/107846213-47d35200-6de2-11eb-9e24-ffa06acc4440.png)

Am i missing something here? 

Best regards,

Michael

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
