### ISSUE TITLE
Vulnerability Finding ID: VUF-22995229, Vulnerability Finding Name: Red Hat Keycloak New Account Console Referrer URL Reflected XSS

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak-community#242]
Vulnerability Finding ID: VUF-22995229
Vulnerability Finding Name: Red Hat Keycloak New Account Console Referrer URL Reflected XSS  
Severity: Medium
Discussion: Red Hat Keycloak New Account Console Referrer URL Reflected XSS. Red Hat Keycloak contains a flaw that allows a reflected cross-site scripting (XSS) attack. This flaw exists because the new account console does not properly sanitize input to the referrer URL before returning it to users. This may allow a context-dependent attacker to create a specially crafted request that executes arbitrary script code in a user's browser session within the trust relationship between their browser and the server.  
CVSS Score: 4.3
Product: Red Hat [Keycloak (12.0.2)]

Vulnerability Finding ID: VUF-22995227     
Vulnerability Finding Name: RedHat Keycloak Account Page First Name / Last Name Field Stored XSS
Severity: Medium
Discussion: RedHat Keycloak Account Page First Name / Last Name Field Stored XSS. RedHat Keycloak contains a flaw that allows a stored cross-site scripting (XSS) attack. This flaw exists because the account page does not properly sanitize input to the 'First Name' and 'Last Name' fields before returning it to users. This may allow an authenticated remote attacker to create a specially crafted request that executes arbitrary script code in a user's browser session within the trust relationship between their browser and the server.
CVSS Score: 4.0
Product: Red Hat [Keycloak (Unspecified)]

**What is the fix for thebove vulnerability?**

**Comment by ashirvadgupta** [comment]
Even I have the same question

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
