### ISSUE TITLE
How to set up a reverse proxy path (KeycloakX/docker)?

### ISSUE THREAD

**Issue by skug67** [keycloak/keycloak-community#245]
I've been running the legacy/wildfly version of Keycloak behind a reverse-proxy at a sub-url (https://my.domain.name/keycloak) which is easy enough to do by replacing "web-context=auth" with "web-context=keycloak/auth" in the standalone.xml file.

I'm trying modernize and streamline my upgrade paths by using docker and Keycloak.X,  It appears that the web path is controlled by "quarkus.http.root-path" which defaults to "/". It seems like it would be easy enough to get what I want if I add "quarkus.http.root-path=/keycloak/" for "/" in the keycloak.properties file.  But when I set up a Dockerfile to do that (RUN echo "quarkus.http.root-path=/keycloak/" >> conf/keycloak.properties) the container errors and crashes out.  I admit wasn't sure about the trailing "/" but the same thing happens if I just use "/keycloak" instead of "/keycloak/" 

Any suggestions?

**Comment by skug67** [comment]
I was able to get it working with KeycloakX outside of docker by changing quarkus.http.root-path=/keycloak in keycloak.properties.  And it is pretty easy to run w/o using docker, so I'm good.  Will leave this open in case others feel more strongly about using docker.

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
