### ISSUE TITLE
Is Keycloak.X estable ?

### ISSUE THREAD

**Issue by clmoreno** [keycloak/keycloak-community#247]
I'm looking for information about Keycloak.X,  got some questions.

- Is Keycloak.X stable ?
- Is it compatible with applications already using "clasic" keycloak?
- Is there any documentation about the differences between X and "clasic" ?
- Is Keycloak.X 12.04 same as Keycloak clasic 12.0.4? (in terms of features, security, usage) i mean is the same version but on quarkus ? 🤔 

Sorry if i'm asking in the wrong place, i didn't find any documentation site for the Keycloak.X version :(

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
