### ISSUE TITLE
Possible issues with ldap mappers

### ISSUE THREAD

**Issue by taigi100** [keycloak/keycloak-community#248]
I have an issue with LDAP mappings. So, if I set my LDAP mappings to things such as "last name mapped to employeeID", it shows up correctly in the big table from Manage -> Users. But, when I click a resource, in the details panel it shows the default.

Also, when I try to /get the resource, I'm getting the default values for last name and so on. Is this how it's supposed to work? Am I missing something?

I tried syncing, various options and so on. Couldn't find anything in the documentation.
Keycloak version: 12.0.3

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
