### ISSUE TITLE
OIDC Session Note Mapper

### ISSUE THREAD

**Issue by zakariae-lebriq** [keycloak/keycloak-community#251]
Hello, 

I have found a display issue when creating an OIDC Client  Session Note Mapper.

Version 12.0.4

![image](https://user-images.githubusercontent.com/59804123/111753713-7936b600-8897-11eb-8dc5-0c0e2a37475b.png)

Regards
Zakariae

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
