### ISSUE TITLE
Import realm file from version 6 to keycloak version 12

### ISSUE THREAD

**Issue by yuling3086** [keycloak/keycloak-community#259]
Hi,
I try to import a realm file which I have in Keycloak version 6 to Keycloak version 12.
Unfortunately it with error "An unexpected server error has occurred"

![image](https://user-images.githubusercontent.com/38518937/112920308-46b07700-913b-11eb-92e2-a04c7900d2a5.png)

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
