### ISSUE TITLE
Application Keyclaok metrics like "User login"

### ISSUE THREAD

**Issue by vnea** [keycloak/keycloak-community#260]
Hello,

In the documentation [here](url), it is said :
>In addition to metrics exposed by WildFly we will expose some Keycloak specific metrics. For example:
>User login
>User login failures
>User count
>Session count
>Client count
>
>Exactly what additional metrics we should expose in the first round is still to be decided.

Do you know when it will be done ?
Because the documentation last update was 23 Sep 2019.

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
