### ISSUE TITLE
Request Party Token reports invalid resource permission

### ISSUE THREAD

**Issue by webfrank** [keycloak/keycloak-community#262]
Hi, I'm trying to setup a simple scenario where a Resource Server will register a resource on Keycloak and gives different access level, with different scopes, to different users.

The Resource Server creates the resource "A" with available scopes "manage" and "view".
Through Resource Server user "A" gives permission to resource "A" with scope "view" to user "B".
When user "B" check for permission using RPT token I got different results based on query parameters.

To get the RPT token I use the Token Endpoint with these parameters:

grant_type: urn:ietf:params:oauth:grant-type:uma-ticket
audience: <<resource server id>>
response_mode: permissions

If I do not specify "permission" params I get the list of resources to which user "B" have access:

`[
    {
        "rsid": "6c8e439f-b641-44d9-a17f-07f0cffc2003",
        "rsname": "resource A"
    },
    {
        "scopes": [
            "view"
        ],
        "rsid": "6c8e439f-b641-44d9-a17f-07f0cffc2003",
        "rsname": "resource A"
    }
]`

I expect to have only one item, "resource A" with scope "view" which is the permission I've granted.

If I specify the param "permission" with value "resource A" this is the reply:

`[
    {
        "scopes": [
            "manage",
            "view"
        ],
        "rsid": "6c8e439f-b641-44d9-a17f-07f0cffc2003",
        "rsname": "resource A"
    }
]`

This time I have only 1 item but I receive also scope "manage" which has not been granted to user "B"

If I ask with "permission" equal to "resource A#view" I receive the expected result:

`[
    {
        "scopes": [
            "tenant:view"
        ],
        "rsid": "6c8e439f-b641-44d9-a17f-07f0cffc2003",
        "rsname": "bizmate"
    }
]`

But if I ask with "permission" equal "resource A#manage" I do not receive 403 but:

`[
    {
        "scopes": [
            "manage",
            "view"
        ],
        "rsid": "6c8e439f-b641-44d9-a17f-07f0cffc2003",
        "rsname": "resource A"
    }
]`

which is totally wrong as I didn't gave permission for scope "manage".

I'm using latest keycloak 12.0.4.

Am I doing something wrong?

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
