### ISSUE TITLE
DB_USER with @ symbol

### ISSUE THREAD

**Issue by mytracks** [keycloak/keycloak-community#268]
We are trying to use Keycloak with the managed PostgreSQL server in Azure. The username is something like `keycloakadmin@dirks-test-westeurope-postgresql`. However, the connection failes because Keycloak seems to clip the name at the `@` symbol. I get an error that the user `keycloakadmin` is not a valid user but the format has to be `username@hostname`. I already tried to use `@@` or `@` instead of the `@`. But that didn't solve the problem.

I run Keycloak in a kubernetes cluster using the keycloak helm chart. The username is set using the environment variable `DB_USER`. I also tried using `DB_USER_FILE` but that results in the same error.

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
