### ISSUE TITLE
REST API Guideline - Documentation section is missing

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-community#27]
Documentation and Swagger/OpenAPI specifications are a critical component of a REST API. This section is missing even though it's probably one of the most imporant sections.

**Comment by abstractj** [comment]
@stianst indeed it's important and we're going to include it for 7.4. Although, we haven't start the implementation around this, which means that this section will remain empty until we do.

**Comment by stianst** [comment]
Moved to https://github.com/keycloak/keycloak/discussions/8499
