### ISSUE TITLE
Implement support for Resource-based RBAC

### ISSUE THREAD

**Issue by imochurad** [keycloak/keycloak-community#273]
As a software architect, I would love to have a chance to assign a role to a resource (instance) of a particular resource type.
The resource ids are not known ahead of time. 

As far as the documentation goes, I haven't noticed mentions of such RBAC implementation. I am curious whether it is supported at all, whether this is on the roadmap. Or, maybe, my ask does not make sense and it is more of a business logic layer concern.

Please see this link for more details: https://docs.empowerid.com/admin/concepts/empoweridrbacoverview

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
