### ISSUE TITLE
Conditional - User Role not working for keycloak 12.0.4

### ISSUE THREAD

**Issue by Yayg** [keycloak/keycloak-community#274]
Good morning,

I'm currently trying to setup role based access control for a specific client on Keycloak. (e.g I'm trying to allow only some users with a specific role to login to a specific client).
I copied and modified the browser flow to make a new flow and included the "Conditional - User Role" in the flow (just after the "User Password Form") but this is unfortunately not working.
I tried multiple variations of this but without success so I'd like to know if I'm doing this the wrong way or if this might be a bug in keycloak.

![bug](https://user-images.githubusercontent.com/4986194/117859600-823c7600-b28f-11eb-9d86-fd99b7d79138.png)

Sincerely,

Rafael Gozlan

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
