### ISSUE TITLE
Unable to update the encryptionPublicKey

### ISSUE THREAD

**Issue by SomeDeveloper13** [keycloak/keycloak-community#276]
I need to be able to update the encryptionPublicKey and the signingCertificate on an existing keycloak instance at the same time.  
I am able to update the signingCertificate through the partial import admin api functionality & through the console.  
However, I could find nowhere to update the encryptionPublicKey through the API or the console. It is ignored by the partial import (like many of the other configs), and has no corresponding field on the console.  

The _only_ place I've found to make the update is to manually update the DB or when it imports the realm from scratch.  
```sql
SELECT * FROM dev.identity_provider_config
WHERE name in ('encryptionPublicKey', 'signingCertificate')
```

We're currently unable to drop the cluster just build it from scratch every time as there is data that is only available in keycloak which would be lost.  

Is there a way that I missed to do this update?  
Command-line tools or an API are preferred, but we could manually maintain it through the console if there is an option I missed.  

If there isn't currently a way to do this, I'd like to make this a feature request.

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
