### ISSUE TITLE
KeyCloak does not refresh External IDP Token

### ISSUE THREAD

**Issue by ayondeep** [keycloak/keycloak-community#277]
We are using KeyCloak (v11.0.2) Identity Brokering to federate authentication to an external IDP. The Identity Provider is of type OpenID Connect v1.0. Additionally, we are using OIDC Authorization Code Flow with PKCE.

We are successfully able to retrieve the tokens from the external IDP based on the following documentation: https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens

However, when the KeyCloak token is refreshed using "refresh_token" grant by the user-agent, the tokens from the external IDP does not get refreshed which is an issue since the tokens from IDP gets expired even though tokens from KeyCloak broker remains active.

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.

**Comment by ayondeep** [comment]
Created a topic in Keycloak community: https://keycloak.discourse.group/t/keycloak-does-not-refresh-external-idp-token/11261. 

Thanks!
