### ISSUE TITLE
Hide client scope from .well-known-configuration

### ISSUE THREAD

**Issue by szanelli-unitn** [keycloak/keycloak-community#279]
Reading Keycloak documentation I undestood that can manage Client Scopes (OAuth compliant) and Authorization Scopes, this last only if enabled throught a specific setting that allow the client to act as a resource server.
Using the first solution, every scope created in Client Scopes is visible inside the .well-known-configuration endpoint.
Is there any option to mark a scope as invisible for .well-known-configuration endpoint to avoid the exposition via the scopes_supported property?

Thanks in advance.

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
