### ISSUE TITLE
Automatically sets the user action to update the password

### ISSUE THREAD

**Issue by Rostish** [keycloak/keycloak-community#280]
Good day collegues.

Keycloak ver: 12.0.4
Keycloack works in LDAP mode. All changes sync from AD.

Sometimes random users have a problem with auth because system(Keycloack) set them user action: update password. Not for all in realm, just for some.

Didn't find anything in doc about such problems.
What scenarios involve automatically exposing a user action? It seems somehow connected with pwdLastSet attribute. My service manually, periodically does fullSync AD -> Keycloak and nothing more. AccountExpire set to never,

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
