### ISSUE TITLE
 request to the redirect_uri path but there's no session state found

### ISSUE THREAD

**Issue by Chinnuganga** [keycloak/keycloak-community#282]
Facing this error while using openidc-resty to add keycloak authentication to an application. The integration works fine when accessed directly through browser.

Now we are looking for SSO while login from Application 1 which is keycloak integrated.
We are trying to load the application2 through an iframe from application1.
The application 2 is integrated with openidc-resty to achieve integration with keycloak.

Now, when we local application2 in an iframe within application1, we are facing the following error

"There was an error while logging in: request to the redirect_uri_path but there's no session state found"

Also we could see some of the keycloak cookies are blocked by browser with the following error

"Set-Cookie didn't specify a "Same-Site" attribute and was defaulted to "Same-Site=Lax", and was blocked because it came from a cross-site response"

The following Keycloak cookies were blocked by this error

KC_RESTART
KEYCLOAK_IDENTITY_LEGACY
KEYCLOAK_SESSION_LEGACY
KEYCLOAK_REMEMBER_ME

Can someone please suggest a solution to this issue?

**Comment by biligee** [comment]
Same here. I need KC_RESTART cookie set as "SameSite=None" to overcome CORB blocking.

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
