### ISSUE TITLE
Accessing Policy/Permissions Endpoints always return empty list.

### ISSUE THREAD

**Issue by kaushiksrinivas** [keycloak/keycloak-community#284]
Hi, 
We are trying to access the Protection API endpoints with respect to resources and permission/policies.
Our intention is to download/fetch all the permission/policies with respect to all the resources under a given client in keycloak server.So to achieve this ,
1. we would want to fetch all resources of type "topic" via the API (curl -v -H "Authorization: Bearer $pat" http://x.x.x.x:x/auth/realms/.com/authz/protection/resource_set?type=topic)
  we are able to get the PAT presenting the client secret and fetch all the resources ids of type "topic" by presenting the PAT  using the above API.

2. fetch all the permission/policies and map them to the resources fetched from step 1.
   the api endpoint to fetch all the permissions :   curl -v -H "Authorization: Bearer $pat" http://x.x.x.x:x/auth/realms/test.com/authz/protection/uma-policy                                                                                                                              This api is always fetching us empty list. Even though the permissions are added in the keycloak server under this client, it does not fetch any data.   We have tried to present the PAT token as well as a normal bearer token using user credentials via below apis. 
             a: PAT token: curl -X POST \    -H "Content-Type: application/x-www-form-urlencoded" \    -d 'grant_type=client_credentials&client_id=kafka-api&client_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \    "http://x.x.x.x:x/auth/realms/test.com/protocol/openid-connect/token"
            b: user credentials with client credentials: sudo curl -d 'client_id=kafka-api&client_secret=xxxxxxxxxxxxxxxxxxxxxxx' -d "username=user" -d "password=123456"  -d "grant_type=password" http://x.x.x.x:x/auth/realms/test.com/protocol/openid-connect/token | jq

**Also, we have tried to access the same via the below private API,
curl --location --request GET 'http://x.x.x.x:x/auth/admin/realms/test.com/clients/d34ab515-c045-4d91-b01b-59d45f89ff70/authz/resource-server/permission?resource=destination1' --header 'Authorization: Bearer <PAT>'** 

But this API is a private API (as it seems to us) and does not have any documentation found in keycloak docs.
Can anyone confirm if the above API (authz/resource-server) can be used in a production grade applications ? or is it subjected to any unnotified deprecations or not get enough support if there are any issues in the API ?

Thanks,
Kaushik.

**Comment by swathimocharla** [comment]
@stianst , can you please take a look at this issue

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
