### ISSUE TITLE
Ability to update Realm ID

### ISSUE THREAD

**Issue by anshulpatel25** [keycloak/keycloak-community#288]
After going through the documentation, I was unable to find a mechanism that can update the Realm ID in the database.
It will be awesome to have documentation, API or CLI to safely update Realm ID as it is seemingly difficult to update it by SQL in the database due to many complicated foreign key constraints on `realm` table.

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
