### ISSUE TITLE
Errors in user administration view

### ISSUE THREAD

**Issue by baltom** [keycloak/keycloak-community#289]
After keycloak 13.x.x and now also 14.0.0 when i navigate to the user administration view in a realm it does not work on mobile (see screenshots). Also when clicking any of the items I get a "Resource not found" page.
![Screenshot_20210622-192913](https://user-images.githubusercontent.com/10920353/122972650-a9a75800-d390-11eb-9759-766a6c959a3e.png)
![Screenshot_20210622-192851](https://user-images.githubusercontent.com/10920353/122972717-b926a100-d390-11eb-8699-4c8993b87c9e.png)

It works just fine on bigger screen (computer)

**Comment by PawelBalcerek** [comment]
I have the same problem even on the bigger screen and I don't know if it isn't an OS problem (what would be weird). Windows 7 / 8.1 / 10 is fine, but on Windows XP with 1920 x 1080 I can't get into the "Users" or "User federation" tabs as well.

**Comment by pbarbashov** [comment]
Also encountered this problem. We solved by updating the browser (checked on new version of Chrome).

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
