### ISSUE TITLE
Offline sessions in cache never get in sync with database 

### ISSUE THREAD

**Issue by aberhallo** [keycloak/keycloak-community#290]
Hi, 

with the update to Keycloak version 13.0.1 (from 12) we are facing the following problem: 

The number of offline tokens for a certain realm in cache never gets in sync/has never the same number as in database. Both values are increasing continously but the cache increases faster. So we have a increasing gap of 
~1000 tokens per day which seem to be only in cache and not in database. We currently have ~460K offline tokens at all in this realm and have a single instance (no shared infinispan). 

As a consequence we expect that in case of a restart the offlines tokens which are only in cache are "lost". 

With v12 both values were equal (or differs in maximal 20 tokens and synced afterwards again). 

Next to this increasing gap we can see several exceptions in the log which we didn't have with v12 and which could be related to this:
![error1](https://user-images.githubusercontent.com/29666652/123119691-09ab0680-d444-11eb-8efb-cba84ab623db.jpg)
![error2](https://user-images.githubusercontent.com/29666652/123119712-0dd72400-d444-11eb-83c0-d6d57326f34d.jpg)
![error3](https://user-images.githubusercontent.com/29666652/123119724-10397e00-d444-11eb-9884-d6951ce1a3c0.jpg)
![error4](https://user-images.githubusercontent.com/29666652/123119732-12034180-d444-11eb-9169-d1fd7cdcaa12.jpg)

Thanks in advance!

**Comment by steffakasid** [comment]
Over night we found out that we were wrong: The db tokens decrease were the offline tokens in the cash increase:
![image](https://user-images.githubusercontent.com/39158011/123222416-36a4fb00-d4d0-11eb-96e0-b256fae5341d.png)

It looks like no new tokens are written into the db.

**Comment by aberhallo** [comment]
Maybe this is a result of https://issues.redhat.com/browse/KEYCLOAK-18539 ?!

**Comment by aberhallo** [comment]
Update: KEYCLOAK-18518 did not fix it, so still an issue :-/

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
