### ISSUE TITLE
keycloak user's sensitive data database encryption

### ISSUE THREAD

**Issue by mazenaissa** [keycloak/keycloak-community#293]
In order to make Keycloak GDPR compliant, how can I encrypt some user's sensitive data in the database?

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.

**Comment by mazenaissa** [comment]
Hello @stianst 
I've declared the request in jira
https://issues.redhat.com/browse/KEYCLOAK-19271
Thanks,
