### ISSUE TITLE
In Keycloak, in User search, on clicking on 'View all user' it is showing an error.

### ISSUE THREAD

**Issue by Shikha10Nagar** [keycloak/keycloak-community#300]
**Keycloak Version :** 12.0.4

**Steps to Reproduce:**
Launch the Keycloak, & login with valid credentials
Go to Users
Click on 'View all users' button to search [It takes some time]
**Actual Result:** An error is displayed "An unexpected server error has occurred"

**Expected Result:** It should show whole list of users

**<img width="952" alt="keycloak_userSearchError" src="https://user-images.githubusercontent.com/88711465/128840161-35623527-da08-499d-9374-0d8bf45d39aa.PNG">** 

![keyclaok consol error](https://user-images.githubusercontent.com/88711465/129016085-02827e10-1b00-4426-9bfb-2cb839da8dcb.JPG)

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
