### ISSUE TITLE
getRoleMappingsStream() doesn't return roles groups

### ISSUE THREAD

**Issue by sy6sy2** [keycloak/keycloak-community#301]
Steps to reproduce:

* Create an user `user1`
* Create a realm role `role1`
* Create a real group `group1`
* Assign `role1` to `group1` in *Role mapping* tab
* Add `user1` in `group1`
* Call `getRoleMappingsStream()` on `user1`
* You expect to have `role1` in the result, but this one is missing.

BUT, if you directly assign `role1` to `user1`, `getRoleMappingsStream()` works as expected.

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
