### ISSUE TITLE
how to set proxy-https to keycloak 12.0.1 in docker 

### ISSUE THREAD

**Issue by oyaranli** [keycloak/keycloak-community#302]
Hello, 

I have a configuration suh as;
- two keycloak running on 8080 and 8443 in docker configured as standalone clusters.
- a load balancer in front of them.  
- load balancer accepts https requests on port 443

Redirections from keycloaks turn out to be http and conducted to the client as http.

Solution seems to be to add a proxy https connector configuration and redirection to it.
Everything told in the documents is performed but cannot create a proxy https connector and redirection of http request to that connector. standalone-ha.xml seems as is without change. Is there a way to make this configuration through ENV variables for instance.

Any help will be appreciated.

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
