### ISSUE TITLE
two application identical client configurations, one working, the other not

### ISSUE THREAD

**Issue by oyaranli** [keycloak/keycloak-community#303]
Hi

In localhost my application works with keycloak without problem . But in test environment with a domain name set for the application, after authenticating I get the following message.

Invalid state: Please reattempt the request *** {"Code":"474e999-5ad8-44b3-9587-4b9aa732ab83.ccb96377-6191-46d9-8f0d-5f2be59b99ed.c2b1a406-b379-412a-bde4-3525cd2c44ad","State":"oidc_state_1f1cf5df1264d74b34bad4282e5f07a","Error":null,"ErrorUri":null,"ErrorDescription":null} *** null

Why could this happen? Any guess?

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
