### ISSUE TITLE
keycloak session when working on 2 or more browser tabs

### ISSUE THREAD

**Issue by sreevidyaJ** [keycloak/keycloak-community#304]
Hi Team,

I have 2 clients in keycloak and i have opened 2 applications in 2 tabs of same browser. Now when I work on  browser tab1, and after some time when I switch to  tab2 the page is automatically refreshed. is there any way where I can update the session without refreshing the page

Thanks,
Sreevidya

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
