### ISSUE TITLE
Unable to export user form keycloak

### ISSUE THREAD

**Issue by Vivek-kapoor** [keycloak/keycloak-community#306]
Hi Team,

I was trying to export users from keycloak but am getting below exception.
![image](https://user-images.githubusercontent.com/21108877/131120233-106df955-1d8a-43cf-94b0-7febfdf0cb53.png)

Keycloak version - 12.0.4
Command executed - 
`bin/standalone.sh
    -Djboss.socket.binding.port-offset=100
    -Dkeycloak.migration.action=export 
    -Dkeycloak.migration.provider=singleFile
    -Dkeycloak.migration.realmName=<REALM_NAME>
    -Dkeycloak.migration.usersExportStrategy=SAME_FILE
    -Dkeycloak.migration.file=/tmp/<REALM_NAME>-users.json`

Can someone please help me with the solution?
Regards
Vivek Kapoor

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
