### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by Muntasir2001** [keycloak/keycloak-community#308]
Hi,

I have a keycloak running in docker and I am using React and Nginx for port forwarding. As I was trying to avoid hardcoding links, I put **relative paths** in config file of keycloak. The following is my keycloak.js which contains the config for keycloak

```js
import Keycloak from 'keycloak-js';

const keycloakConfig = {
	url: '/auth/',
	realm: 'myrealm',
	clientId: 'myapp',
};

const keycloak = new Keycloak(keycloakConfig);
export default keycloak;
```

Notice the relative path in 'url'. I am assuming here that this will add '/auth/' to my current url (no matter what the url is). I have this path set to keycloak url in nginx.

nginx.conf
```text
server {

   listen 80;

   location /auth {
      proxy_pass http://keycloak:8080;
      proxy_set_header    Host               $host;
      proxy_set_header    X-Real-IP          $remote_addr;
      proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
      proxy_set_header    X-Forwarded-Host   $host;
      proxy_set_header    X-Forwarded-Server $host;
      proxy_set_header    X-Forwarded-Port   $server_port;
      proxy_set_header    X-Forwarded-Proto  $scheme;
      # proxy_set_header Host $host; 
      # proxy_set_header X-Real-IP  $remote_addr; 
      # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # proxy_buffers 4 16k;
   }
}
```

Changing the url to relative path in keycloak.js has broken the redirect URL after signing up (the login redirect URL works perfectly fine) and I wonder why. The error message says that the issue is with nginx conf. This is the error message which shows up in the browser:

![Screenshot 2021-09-02 at 17 24 16](https://user-images.githubusercontent.com/52258261/131881261-077cf507-c738-4c69-9e58-e4d2cdc8a52f.png)

I haven't seen any error messages in the terminal. 

I never seen this issue when I had my url hardcoded to http://localhost:8080.

This could be because I am doing something wrong (as this is my first time working with keycloak, nginx and docker). 

Any help would be appreciated.

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
