### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by rahim86** [keycloak/keycloak-community#309]
With latest code, I'm getting below error. Full trace attached as well

[ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:4.2.8.Final:provision (server-provisioning) on project keycloak-server-dist: Provisioning failed: Feature-pack archive does not contain feature-pack.xml -

[INFO] Reactor Summary for Keycloak 16.0.0-SNAPSHOT:
[INFO] 
[INFO] Keycloak BOM Parent ................................ SUCCESS [  1.742 s]
[INFO] Keycloak BOM for adapters .......................... SUCCESS [  0.030 s]
[INFO] Keycloak BOM for server extensions ................. SUCCESS [  0.025 s]
[INFO] Keycloak BOM utilities for the quickstarts ......... SUCCESS [  0.021 s]
[INFO] Keycloak ........................................... SUCCESS [  0.081 s]
[INFO] Keycloak Common .................................... SUCCESS [  5.543 s]
[INFO] Keycloak Core ...................................... SUCCESS [  7.933 s]
[INFO] Keycloak Server SPI ................................ SUCCESS [  3.979 s]
[INFO] Keycloak Kerberos Federation ....................... SUCCESS [  0.447 s]
[INFO] Keycloak LDAP UserStoreProvider .................... SUCCESS [  2.404 s]
[INFO] Keycloak SAML Core Public API ...................... SUCCESS [  1.528 s]
[INFO] Keycloak SAML Core ................................. SUCCESS [  5.198 s]
[INFO] Keycloak REST Services ............................. SUCCESS [ 18.769 s]
[INFO] Keycloak JS Integration ............................ SUCCESS [  2.946 s]
[INFO] Keycloak Themes .................................... SUCCESS [01:31 min]
[INFO] Keycloak Dependencies Parent ....................... SUCCESS [  0.017 s]
[INFO] Keycloak Dependencies Server Min ................... SUCCESS [  0.018 s]
[INFO] Keycloak Model Parent .............................. SUCCESS [  0.028 s]
[INFO] Keycloak Model JPA ................................. SUCCESS [  3.304 s]
[INFO] Keycloak Model Map ................................. SUCCESS [  2.520 s]
[INFO] Keycloak Model Infinispan .......................... SUCCESS [  6.216 s]
[INFO] Keycloak SSSD Federation ........................... SUCCESS [  1.135 s]
[INFO] KeyCloak Authz: Parent ............................. SUCCESS [  0.017 s]
[INFO] KeyCloak AuthZ: Provider Parent .................... SUCCESS [  0.018 s]
[INFO] KeyCloak AuthZ: Common Policy Providers ............ SUCCESS [  0.510 s]
[INFO] Keycloak Dependencies Server All ................... SUCCESS [  0.046 s]
[INFO] Keycloak Federation ................................ SUCCESS [  0.022 s]
[INFO] Keycloak Util Embedded LDAP ........................ SUCCESS [  0.909 s]
[INFO] Keycloak Util Parent ............................... SUCCESS [  0.022 s]
[INFO] Keycloak WildFly Integration ....................... SUCCESS [  0.019 s]
[INFO] Keycloak WildFly Add User Script ................... SUCCESS [  0.452 s]
[INFO] Keycloak WildFly Extensions ........................ SUCCESS [  2.146 s]
[INFO] Keycloak WildFly Server Subsystem .................. SUCCESS [  4.425 s]
[INFO] Keycloak Integration ............................... SUCCESS [  0.019 s]
[INFO] Keycloak Admin REST Client ......................... SUCCESS [  0.681 s]
[INFO] Keycloak Client Registration API ................... SUCCESS [  0.234 s]
[INFO] Keycloak Client CLI ................................ SUCCESS [  0.016 s]
[INFO] Keycloak Client Registration CLI ................... SUCCESS [  3.368 s]
[INFO] Keycloak Admin CLI ................................. SUCCESS [  2.938 s]
[INFO] Keycloak Client CLI Distribution ................... SUCCESS [  0.930 s]
[INFO] Keycloak Adapter SPI ............................... SUCCESS [  0.390 s]
[INFO] Keycloak Tomcat Adapter SPI ........................ SUCCESS [  0.200 s]
[INFO] Keycloak Undertow Integration SPI .................. SUCCESS [  0.384 s]
[INFO] Keycloak Servlet Integration ....................... SUCCESS [  0.288 s]
[INFO] Common JBoss/Wildfly Core Classes .................. SUCCESS [  0.274 s]
[INFO] Keycloak Jetty Adapter SPI ......................... SUCCESS [  0.308 s]
[INFO] Keycloak Client Adapter SPI Modules ................ SUCCESS [  0.014 s]
[INFO] Keycloak SAML Client Adapter Public API ............ SUCCESS [  0.187 s]
[INFO] Keycloak SAML Client Adapter Core .................. SUCCESS [  2.613 s]
[INFO] Keycloak Undertow SAML Adapter ..................... SUCCESS [  0.307 s]
[INFO] Keycloak SAML Tomcat Integration ................... SUCCESS [  0.016 s]
[INFO] Keycloak Tomcat Core SAML Integration .............. SUCCESS [  0.357 s]
[INFO] Keycloak Tomcat SAML Integration ................... SUCCESS [  0.268 s]
[INFO] Keycloak Tomcat 7 SAML Integration ................. SUCCESS [  0.202 s]
[INFO] Keycloak Wildfly SAML Adapter ...................... SUCCESS [  0.455 s]
[INFO] KeyCloak Authz: Client API ......................... SUCCESS [  0.559 s]
[INFO] Keycloak Adapter Core .............................. SUCCESS [  2.722 s]
[INFO] Keycloak WildFly Elytron SAML Adapter .............. SUCCESS [  0.395 s]
[INFO] Keycloak Wildfly SAML Adapter Subsystem ............ SUCCESS [  3.960 s]
[INFO] Keycloak SAML Wildfly Integration .................. SUCCESS [  0.021 s]
[INFO] Keycloak SAML Servlet Filter ....................... SUCCESS [  0.222 s]
[INFO] Keycloak Jetty Core SAML Integration ............... SUCCESS [  0.360 s]
[INFO] Keycloak Jetty 9.2.x SAML Integration .............. SUCCESS [  0.455 s]
[INFO] Keycloak Jetty 9.3.x SAML Integration .............. SUCCESS [  0.391 s]
[INFO] Keycloak Jetty 9.4.x SAML Integration .............. SUCCESS [  0.375 s]
[INFO] Keycloak SAML Jetty Integration .................... SUCCESS [  0.015 s]
[INFO] Keycloak AS7 / JBoss EAP 6 Integration ............. SUCCESS [  0.024 s]
[INFO] Keycloak AS7 SPI ................................... SUCCESS [  1.743 s]
[INFO] Keycloak SAML EAP Integration ...................... SUCCESS [  0.015 s]
[INFO] Keycloak SAML AS7 Integration ...................... SUCCESS [  0.434 s]
[INFO] Keycloak SAML AS7 Subsystem ........................ SUCCESS [  3.694 s]
[INFO] Keycloak SAML Client Adapter Modules ............... SUCCESS [  0.014 s]
[INFO] Keycloak Installed Application ..................... SUCCESS [  0.249 s]
[INFO] Keycloak Undertow Integration ...................... SUCCESS [  0.384 s]
[INFO] Keycloak Fuse 7.0 Integration ...................... SUCCESS [  0.015 s]
[INFO] Keycloak Fuse 7.0 Adapter - Camel + Undertow ....... SUCCESS [  0.933 s]
[INFO] Keycloak OSGI Adapter .............................. SUCCESS [  1.460 s]
[INFO] Keycloak Fuse 7.0 Adapter - Undertow ............... SUCCESS [  0.574 s]
[INFO] Keycloak Jetty Core Integration .................... SUCCESS [  0.338 s]
[INFO] Keycloak Jetty 9.4.x Integration ................... SUCCESS [  0.314 s]
[INFO] Keycloak Fuse 7.0 Adapter - Jetty 9.4 .............. SUCCESS [  0.450 s]
[INFO] Keycloak Tomcat Integration ........................ SUCCESS [  0.025 s]
[INFO] Keycloak Tomcat Core Integration ................... SUCCESS [  0.270 s]
[INFO] Keycloak Tomcat Integration ........................ SUCCESS [  0.297 s]
[INFO] Keycloak Fuse 7.0 Adapter - Tomcat 8 ............... SUCCESS [  0.431 s]
[INFO] Keycloak CLI SSO Framework ......................... SUCCESS [  2.373 s]
[INFO] Keycloak JAX-RS OAuth Client ....................... SUCCESS [  0.270 s]
[INFO] Keycloak Jetty 9.2.x Integration ................... SUCCESS [  0.306 s]
[INFO] Keycloak Jetty 9.3.x Integration ................... SUCCESS [  0.318 s]
[INFO] Keycloak Jetty Integration ......................... SUCCESS [  0.016 s]
[INFO] Keycloak Servlet Filter Adapter Integration ........ SUCCESS [  0.390 s]
[INFO] spring-boot-container-bundle ....................... SUCCESS [  0.268 s]
[INFO] spring-boot-legacy-container-bundle ................ SUCCESS [  0.167 s]
[INFO] Keycloak Spring Security Integration ............... SUCCESS [  3.267 s]
[INFO] Keycloak Spring Boot Adapter Core .................. SUCCESS [  0.518 s]
[INFO] Keycloak Spring Boot Integration ................... SUCCESS [  1.805 s]
[INFO] Keycloak Spring Boot 2 Integration ................. SUCCESS [  1.933 s]
[INFO] Keycloak Tomcat 7 Integration ...................... SUCCESS [  0.255 s]
[INFO] Keycloak Wildfly Integration ....................... SUCCESS [  0.278 s]
[INFO] Keycloak Wildfly Elytron OIDC Adapter .............. SUCCESS [  0.391 s]
[INFO] Keycloak Wildfly Adapter Subsystem ................. SUCCESS [  4.100 s]
[INFO] Keycloak WildFly Integration ....................... SUCCESS [  0.016 s]
[INFO] Keycloak AS7 Integration ........................... SUCCESS [  0.309 s]
[INFO] Keycloak AS7 Subsystem ............................. SUCCESS [  1.672 s]
[INFO] Keycloak OIDC Client Adapter Modules ............... SUCCESS [  0.017 s]
[INFO] Keycloak Adapters .................................. SUCCESS [  0.015 s]
[INFO] Keycloak Misc ...................................... SUCCESS [  0.014 s]
[INFO] Keycloak :: Spring :: Boot ......................... SUCCESS [  0.015 s]
[INFO] Keycloak :: Spring :: Boot :: Default ::  Starter .. SUCCESS [  0.122 s]
[INFO] Keycloak :: Spring :: Boot ......................... SUCCESS [  0.018 s]
[INFO] Keycloak :: Legacy :: Spring :: Boot :: Default ::  Starter SUCCESS [  0.097 s]
[INFO] keycloak-test-helper ............................... SUCCESS [  0.352 s]
[INFO] Keycloak Quarkus Parent ............................ SUCCESS [  0.015 s]
[INFO] Keycloak Quarkus Server Extension .................. SUCCESS [  6.209 s]
[INFO] Keycloak Quarkus Server Deployment ................. SUCCESS [ 51.327 s]
[INFO] Keycloak Quarkus Server App ........................ SUCCESS [  6.748 s]
[INFO] Keycloak OSGI Features ............................. SUCCESS [  0.161 s]
[INFO] Keycloak OSGI JAAS Realm Configuration ............. SUCCESS [  0.218 s]
[INFO] Distribution Parent ................................ SUCCESS [  0.017 s]
[INFO] Keycloak Distribution Licenses Common .............. SUCCESS [  3.743 s]
[INFO] Keycloak Distribution Maven Plugins Parent ......... SUCCESS [  0.094 s]
[INFO] Keycloak Licenses Processor Maven Plugin ........... SUCCESS [  3.673 s]
[INFO] Keycloak Fuse Adapter Distro ....................... SUCCESS [  2.135 s]
[INFO] Keycloak JS Adapter Distribution ................... SUCCESS [  0.186 s]
[INFO] Keycloak OSGI Integration .......................... SUCCESS [  0.015 s]
[INFO] Feature Pack Builds ................................ SUCCESS [  0.014 s]
[INFO] Keycloak Feature Pack: Adapter ..................... SUCCESS [  3.072 s]
[INFO] Adapters Distribution Parent ....................... SUCCESS [  0.021 s]
[INFO] Keycloak Adapter Overlay Distribution .............. SUCCESS [  1.993 s]
[INFO] Keycloak Tomcat Adapter Distro ..................... SUCCESS [  2.818 s]
[INFO] Keycloak Tomcat 7 Adapter Distro ................... SUCCESS [  1.382 s]
[INFO] Keycloak Jetty 9.2.x Adapter Distro ................ SUCCESS [  1.217 s]
[INFO] Keycloak Jetty 9.3.x Adapter Distro ................ SUCCESS [  1.215 s]
[INFO] Keycloak Jetty 9.4.x Adapter Distro ................ SUCCESS [  1.502 s]
[INFO] Keycloak JS Adapter NPM Distribution ............... SUCCESS [  0.088 s]
[INFO] Keycloak AS7 / JBoss EAP 6 Adapter Distros ......... SUCCESS [  0.022 s]
[INFO] Keycloak AS7 / JBoss EAP 6 Modules ................. SUCCESS [  2.468 s]
[INFO] Keycloak JBoss EAP 6 Adapter Distro ................ SUCCESS [  1.188 s]
[INFO] Keycloak AS7 Adapter Distro ........................ SUCCESS [  1.197 s]
[INFO] Keycloak SAML Wildfly Modules ...................... SUCCESS [  0.508 s]
[INFO] Keycloak SAML Wildfly Adapter Distro ............... SUCCESS [  0.403 s]
[INFO] Keycloak Wildfly SAML Adapter ...................... SUCCESS [  0.014 s]
[INFO] Keycloak SAML Jetty 9.2.x Adapter Distro ........... SUCCESS [  2.544 s]
[INFO] Keycloak SAML Jetty 9.3.x Adapter Distro ........... SUCCESS [  1.694 s]
[INFO] Keycloak SAML Jetty 9.4.x Adapter Distro ........... SUCCESS [  1.673 s]
[INFO] Keycloak SAML Tomcat Adapter Distro ................ SUCCESS [  1.738 s]
[INFO] Keycloak SAML Tomcat 7 Adapter Distro .............. SUCCESS [  1.750 s]
[INFO] Keycloak SAML AS7 / JBoss EAP 6 Adapter Distros .... SUCCESS [  0.012 s]
[INFO] Keycloak SAML AS7 / JBoss EAP 6 Modules ............ SUCCESS [  0.702 s]
[INFO] Keycloak SAML JBoss EAP 6 Adapter Distro ........... SUCCESS [  0.945 s]
[INFO] Keycloak SAML AS7 Adapter Distro ................... SUCCESS [  0.865 s]
[INFO] SAML Adapters Distribution Parent .................. SUCCESS [  0.013 s]
[INFO] Keycloak Feature Pack: Server Dependencies ......... SUCCESS [  0.016 s]
[INFO] Keycloak Feature Pack: Server ...................... SUCCESS [ 11.508 s]
[INFO] Galleon Feature Pack Builds ........................ SUCCESS [  0.013 s]
[INFO] Keycloak Galleon Feature Pack: Adapter ............. SUCCESS [ 11.783 s]
[INFO] Keycloak Galleon Feature Pack: Server .............. SUCCESS [ 29.014 s]
[INFO] Keycloak Server Galleon Based Distribution ......... FAILURE [  0.199 s]
[INFO] Keycloak Server Overlay Distribution ............... SKIPPED
[INFO] Keycloak.X Server Distribution ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:20 min
[INFO] Finished at: 2021-09-04T08:59:51-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:4.2.8.Final:provision (server-provisioning) on project keycloak-server-dist: Provisioning failed: Feature-pack archive does not contain feature-pack.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
