### ISSUE TITLE
Unable to get access token when sending "code_verifier" within jwt when pkce is enabled

### ISSUE THREAD

**Issue by mukulsinghsaini** [keycloak/keycloak-community#311]
I am using Microsoft.AspNetCore.Authentication.OpenIdConnect library.

Keycloak is able to  find code_verifier and works fine when using this
`context.TokenEndpointRequest.Parameters.Add("code_verifier", "some code");`

If I pass code_verifier within the jwt in client_assertion, keycloak fails to find code_verifier

I have also tried sending code_verifier in a jwt in "request" parameter as per [https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests](url). Still keycloak fails to find it.

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
