### ISSUE TITLE
Missing Email attribute in Keycloak first broker login page

### ISSUE THREAD

**Issue by madeinindiadot** [keycloak/keycloak-community#314]
- Configured Microsoft web apps with OIDC in Keycloak. 
- Added identity provider mappers in Keycloak to fetch the user related details (email, name, first name and last name) in the First Broker Login page. 
- On successful authentication Keycloak displays an update page with email field as empty. 
- Microsoft web application is sending those details to Keycloak but Keycloak is failing to fetch it from the response. 
- Is that bug from Keycloak side? can you provide additional information on how email attribute can be configured from the microsoft JWT response to the first broken login page screen with email, first, last and username fields for a particular realm identity provider login credentials store. 
p.s: we are using keycloak database to store all the keycloak information
keycloak versions: 12.01, 13.0.0
platform: kubernetes

**Comment by madeinindiadot** [comment]
any updates?

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
