### ISSUE TITLE
OIDC Identity Provider Claim to Role only looks at User Info

### ISSUE THREAD

**Issue by joao-rebelo** [keycloak/keycloak-community#316]
I'm trying to setup a claim to role mapper on my OIDC Identity Provider, where the claim (ream_access.roles) was comming at the access token.

This was not working since at org.keycloak.broker.oidc.mappers.AbstractClaimMapper::getClaimValue only uses the KeycloakOIDCIdentityProvider.VALIDATED_ACCESS_TOKEN which is only used for Keycloak OIDC providers.

I would expect, and just confirmed with oficial documentation, that any OIDC provider access token could be used for such claim mapping. Namely this means I would expect the OIDCIdentityProvider::processAccessTokenResponse would add the token to the context.

the workaround was to change the refault role mapping to also add the realm_access.roles into the user info.. but this is not documented anywhere I could find beside debugging Keycloak.

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
