### ISSUE TITLE
Default Hostname Provider - feedback

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-community#34]
1) am I understand correctly that "url" and "backChannelUrlFromRequest" are the options of provider defined in standalone.xml? And the additional option "url" will be  at realm-level with the ability to override the "url" configured at standalone.xml level?

2) Not sure if "url" should be renamed to something more explicit like "frontchannelUrl" or "browserUrl" ? It is not super-clear from the name of the option what the "url" actually means.

3) backChannelUrlFromRequest - It is not super-clear to me from the name of this option and from the description how it works? I guess that when it's true, it will mean that backchannelURL should always use request even if "frontchannelUrl" is configured. If it is false, then backchannel url will always use the configured "frontchannelUrl" and never use the URL from the request. So if I understand correctly, the default value should be true rather than false?

4) So with the proposed design, the "auth-server-url" configured on adapter's side will be usually backchannel URL. This means that if I have application deployed on 2 different datacenters and also keycloak server deployed on 2 different datacenters, I may need different application bundles for each datacenter. Reason is, that I usually want that application deployment on datacenterX will access Keycloak server on same datacenterX. Hence the "auth-server-url" in the application deployed on DC1 will be something like "https://keycloak.mycompany.local-dc1/auth" and on DC2 something like "https://keycloak.mycompany.local-dc2/auth" . This is fine for our java adapters as they can use system properties for the stuff configured in keycloak.json . So the adapter in DC1 will be started with something like "-Dauth.server.url=https://keycloak.mycompany.local-dc1/auth" . For some other adapters, they will need 2 corresponding bundles to be able to configure different "auth-server-url" for each datacenter.

I am not sure if this rather corner case or if it is still possible to improve somehow? I can see something like this:
- On keycloak server side, there can be an option somewhere like "backchannelURL" with the value like "https://keycloak.${domain-url}:8443/auth" .
- On adapter side, there will be "auth-server-url" pointing to frontchannel URL of keycloak server like "https://auth.mycompany.com" .
- When the request to OIDC WellKnown endpoint is sent, the Keycloak will read the remote host from "httpRequest.getRemoteHost()" and it detects that it comes from the IP address of the host like "application.mycompany.local-dc1" .
- The backchannel URLs like "token_url" returned from the OIDC WellKnown endpoint will use the value of configured "backchannelURL" replaced with the domain from remote request. So it will be something like "https://keycloak.mycompany.local-dc1:8443/auth" .
- This allows that on application side, it will be single bundle with same "auth-server-url" on all datacenters, but still there will be a way that application on each DC will use the Keycloak server on corresponding datacenter for backchannel requests.
- I am not sure where is good place for the "backchannelURL" option. Configuring on client level won't work as OIDC WellKnown provider is not client specific and Keycloak won't know from which client the request was sent. Configuring at realm or standalone.xml level is probably too generic as every client may have different preferences...

So I am not sure if something like I mentioned in point 4 is just a corner case or not. Maybe we can wait to more feedback before doing something like this... Also will be good to think about various cases in Openshift environments.

**Comment by stianst** [comment]
1. Yes, "url" and "backChannelUrlFromRequest" are options in standalone.xml (server-wide), while there would be an option to override URL for an individual realm. Furhter, it should be possible to use custom domain/paths for a realm. For example a LB should be able to point "https://auth.company.com" to "https://keycloak.company.internal/auth/realms/external".

**Comment by stianst** [comment]
2. I agree "url" is not the best name, not sure I like "frontchannelUrl" or "browserUrl" either though. What about "frontendUrl" or "publicUrl"?

**Comment by stianst** [comment]
3. backChannelUrlFromRequest - the idea here is basically if it's true then you allow internal clients to invoke Keycloak using an internal URL, while allowing external clients to invoke using an external URL. As such the actual URL is based on the request, rather than a hardcoded value. It's perfectly fine from a security perspective to allow this, the important URLs that we can't securely infer from the request are "frontchannelUrls". I appreciate the name is maybe not the most obvious, but not sure what a better name would be.

**Comment by stianst** [comment]
4. Yes, but that would always be the case. You would always have to configure the adapter differently if it needs to use different URLs to access Keycloak. The benefit of this approach compared to having different URLs for frontend/backend requests in adapter is obviously that the adapter only needs a single URL (and also that we can control the actual URLs used through the discovery endpoint based on config on the Keycloak server side)

**Comment by stianst** [comment]
For your corner case - in most cases building back-channel URLs on request is perfectly fine. The only time you want to prevent that is if you explicitly don't want any clients to use internal URLs. The adapter should and has to be configured to the correct URL and that would be the responsibility of whoever deploys it to configure it correctly based on the deployment. Trying to map that on the Keycloak server side would be complex to handle/maintain. Also, remember this is a public SPI so if anyone has strange requirements they can implement their own hostname provider.

**Comment by stianst** [comment]
Made a few changes to try to cover your comments:

* url renamed to frontendUrl
* backChannelUrlFromRequest renamed to forceBackendUrlToFrontendUrl
* Mentioned explicitly that frontendUrl and forceBackendUrlToFrontendUrl are options in standalone.xml
* Expanded to section for realm URL override

**Comment by mposolda** [comment]
@stianst Thanks, I like better the "FrontendUrl" and "forceBackendUrlToFrontendUrl" and it's much clearer now IMO.

Regarding the point 4 and the corner-case scenario, I agree that we can keep the design as is for now. We can eventually expand later based on the feedback on users. Hopefully in most cases, when people really have application deployments in multiple datacenters and hence want to use different "auth-server-url", they are able to "externalize" the difference somehow and not require to have different application bundle for each datacenter. By "externalize" I mean something like use system property substitution for property "auth-server-url" in keycloak.json like we support for our java adapters.

Should this issue be closed now?

**Comment by mposolda** [comment]
BTV. If this issue is closed, will it makes sense to always update the particular design page with the reference to all the issues related to it?

I am thinking of that because someone may want to search issues/discussions related to particular design? The mailing list like keycloak-dev can be always searched for history (even if discussions are sometime bit long and messy), but not sure if we can easily search the history of github issues.

**Comment by stianst** [comment]
Added links to the end of the doc: https://github.com/keycloak/keycloak-community/blob/master/design/hostname-default-provider.md#discussions-and-relevant-information

**Comment by stianst** [comment]
I agree it would be useful to link to feedback on GitHub issues and mailing list, and other relevant information in the proposal.

**Comment by mposolda** [comment]
@stianst Thanks, should this be closed now?
