### ISSUE TITLE
User Profile - feedback

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-community#35]
1) Attributes tab in admin console - it currently contains all the attributes for the user. I think that for attributes with missing key in user profile, it may be good to keep this behaviour and have the attribute still displayed here as editable? Also it may be good if administrator is allowed to add new attribute to the user even if attribute definition is missing in user profile.

2) I am not sure about the difference between Crafted and Dynamic forms. Is crafted form something like form with few known hardcoded profile attributes where dynamic form will be dynamically rendered? I am asking because Crafted form has in description something like "fields are shown or hidden based on user profile", which implies that it is somehow dynamic as well? IMO it will be good if it's possible to have Dynamic forms.

3) Regarding dynamic forms, it may be nice if administrator has ability to define his own "displayer" and "model converter" for the custom types shown in the UI?

For example user will have attribute "birthdate" shown in the UI and the type of this field will be "date" . I can imagine that there is "displayer" for the type "date" in the UI, which will allow user to easily select year, month and day. Then there will be a responsibility of "model converter" to properly convert the selected date from format like "2019-09-10" to the integer format, which will be saved to the DB as number of seconds since 1970-1-1. When the form is shown again in the UI, the "model converter" should be able to convert the integer from the DB and update the UI with the proper content and then "displayer" will render the HTML in the UI shown to the user.

I think that SPI for "displayer" and "model converter" will be nice, so administrator can easily add their own types if they want? I guess this won't be a priority 1 and may need to be added at some later stage based on feedback?

4) User federation - Currently the "view" and "edit" fields in the specification doesn't have any support for user federation or identity brokering. IMO it will be very common use-case that administrator has read-only LDAP. Hence users imported from LDAP will have all the attributes (firstName, lastName, email etc) shown as read-only in the UI, but all the other users have them editable. It seems there are 2 ways how to address this use-case:
(a) Have single definition of "firstName" attribute in user profile, but expand somehow on the fields like "view" and "edit", so they have some support for user federation and identity brokering.
(b) Have multiple definitions of "firstName" attribute in user profile. Like one definition for LDAP users and another for non-LDAP users.

Option (b) seems to be better. If we choose (a), we may think from the beginning about the JSON format of "view" and "edit" and count with user federation and identity brokering from the beginning.

**Comment by stianst** [comment]
1. I disagree - allowing admins to add arbitrary attributes should not be supported. Remember an admin could just be a manager of a group of people, not a sysadmin of Keycloak. Any attributes editable by admins should be listed in the user profile and should be marked as editable by admins, with corresponding validation. Basically, it is not a "user manager" that should control what attributes can be set on a user, but rather a "realm manager" that is configuring the realm and what attributes should be available for users.

**Comment by stianst** [comment]
2. A crafted form will have a registration form with many built-in attributes available. They will be hidden/shown depending on the user profile. This allows us to design a proper form without additional metadata in the user profile. A dynamic form is fully dynamically crafted taking input from the user profile for labels, input types, etc.. I believe a crafted form with more built-in attributes will be sufficient for most that don't want greater control and those that want greater control will want to create a custom registration form regardless, so I think the dynamic form just makes it harder to create the user profile (as you need to add labels, input types, ordering, etc.) and will not actually be all that useful.

**Comment by stianst** [comment]
3. I see this as yet another argument not to support the dynamic form approach, but rather just go for a properly crafted form.

**Comment by stianst** [comment]
4. For user federation I wonder if we somehow could get information from LDAP providers on what fields should be read-only. As otherwise the user profile becomes quite complex as "firstName" could be read/write for users in KC db, read-only from AD, read/write from another LDAP provider, etc.

**Comment by mposolda** [comment]
>     1. I disagree - allowing admins to add arbitrary attributes should not be supported. Remember an admin could just be a manager of a group of people, not a sysadmin of Keycloak. Any attributes editable by admins should be listed in the user profile and should be marked as editable by admins, with corresponding validation. Basically, it is not a "user manager" that should control what attributes can be set on a user, but rather a "realm manager" that is configuring the realm and what attributes should be available for users.

I see.

One thing is, that it is currently quite easy to add some random attribute to the user in the admin console. This is quite nice especially when I want to quickly test something. It won't be so nice if there is a hard requirement to require definition of particular attribute in user profile to be able to add the attribute. Perhaps maybe when we have support for "profiles" like dev/prod, it can be cool to allow adding custom attributes in "dev" mode without a need to have them defined in user profile?

**Comment by mposolda** [comment]
2, 3 Ok, thanks for clarify. My guess is, that people will request dynamic forms, but we can possibly wait for the feedback.

**Comment by mposolda** [comment]
> 4. For user federation I wonder if we somehow could get information from LDAP providers on what 
> fields should be read-only. As otherwise the user profile becomes quite complex as "firstName" could 
> be read/write for users in KC db, read-only from AD, read/write from another LDAP provider, etc.

Yes, so UserFederation SPI and IdentityBrokering SPI will have some new methods to return readable and editable attributes for user and admin? That will probably work.
