### ISSUE TITLE
Failure trying to build keycloak 8.0.1

### ISSUE THREAD

**Issue by victropolis** [keycloak/keycloak-community#41]
It's trying to pull in `org.glassfish.jaxb:txw2:jar:2.4.0-b180608.0325` for some reason.  Thoughts?

```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:tree (default-cli) on project keycloak-saml-core-public: Cannot build project dependency graph: Could not resolve nor collect following dependencies: [org.glassfish.jaxb:txw2:jar:2.4.0-b180608.0325 (compile)]: Could not resolve dependencies for project org.keycloak:keycloak-saml-core-public:jar:8.0.1: Failure to find org.glassfish.jaxb:txw2:jar:2.4.0-b180608.0325 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of repo1 has elapsed or updates are forced -> [Help 1]```

**Comment by akleemans** [comment]
I have the same problem here:

```
Execution failed for task ':keycloak-mappers:compileJava'.
> Could not resolve all files for configuration ':keycloak-mappers:compileClasspath'.
   > Could not find org.glassfish.jaxb:txw2:2.4.0-b180608.0325.
     Searched in the following locations:
       - ...
     Required by:
         project :keycloak-mappers > org.glassfish.jaxb:jaxb-runtime:2.3.1
   > Could not find org.glassfish.jaxb:txw2:2.4.0-b180608.0325.
     Searched in the following locations:
       - ...
     Required by:
         project :keycloak-mappers > org.keycloak:keycloak-saml-core-public:8.0.1 > com.sun.xml.ws:rt:2.3.1 > com.sun.xml.ws:policy:2.7.5

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

But `org.glassfish.jaxb:txw2:2.4.0-b180608.0325` does not exist in a public maven repository (for example https://mvnrepository.com/artifact/org.glassfish.jaxb/txw2).

I tried the clean step and deleted my Gradle cache but nothing seems to work.

**Comment by starJammer** [comment]
I'm having the same issue. I don't understand how version 8.0.1 was published if it can't build. Maybe redhat has some internal repos?

**Comment by starJammer** [comment]
I think I found it: https://repository.jboss.org/nexus/content/repositories/m2-proxy/org/glassfish/jaxb/txw2/

**Comment by starJammer** [comment]
Here as well there is a copy of it: https://repository.jboss.org/nexus/content/repositories/m2-release-proxy/org/glassfish/jaxb/txw2/

**Comment by stianst** [comment]
Please use JIRA to report issues against Keycloak. See keycloak.org/community for more details.
