### ISSUE TITLE
Unable to invalidate access token

### ISSUE THREAD

**Issue by joshisimt** [keycloak/keycloak-community#42]
Hi Team, 

I am trying to invalidate the access token on logout, but unable to do so.
I am calliing this api- http://localhost:8080/auth/realms/Realmname/protocol/openid-connect/logout to logout and invalidate the refresh token. This successfully invalidates the refresh token but not invalidate the access token.

Can you please tell how I can invalidate the access token?

Thanks

**Comment by pedroigor** [comment]
Hi @joshisimt, this is not the appropriate channel for such questions. Please, send a message to https://groups.google.com/forum/#!forum/keycloak-user.
