### ISSUE TITLE
Not able to set realm level role to client scopes through keycloak admin cli

### ISSUE THREAD

**Issue by aarti-stack** [keycloak/keycloak-community#43]
I am using keycloak as a access manager for the client Spring cloud data flow.I am trying to register the client through the Keycloak Admin CLI.

I was able to created all the steps needed to register client except one.

I am unable to set realm -level role to the client scopes using Admin CLI ./kcadm.sh. 

Referred the Rest API documentation https://www.keycloak.org/docs-api/8.0/rest-api/index.html#_scope_mappings_resource

I am trying to construct ./kcadm.sh command using the following :

Add a set of realm-level roles to the client’s scope
POST /{realm}/client-scopes/{id}/scope-mappings/realm

I tried using add ,create and update commands but unable to execute successfully.

**Comment by stianst** [comment]
Please use JIRA to report issues against Keycloak. See keycloak.org/community for more details.
