### ISSUE TITLE
Fail import realm

### ISSUE THREAD

**Issue by pparthenhs** [keycloak/keycloak-community#45]
I created a `realm`, I defined one new client as `confidential` also I create a role and assign it into a new user. At last, I export the realm in order to use it as is in the future. When I tried to import in I received the following error message. 

> Error! An unexpected server error has occurred

![image](https://user-images.githubusercontent.com/9752042/72523598-d173c180-3868-11ea-96c1-cfc7f6480a5e.png)

I am running keycloak as a docker container. In more detail I running version `quay.io/keycloak/keycloak:8.0.1`. I also notice that error occurred only when my imported JSON contains a confidential client, otherwise it works perfectly.

I remain at your disposal for any further information.

**Comment by stianst** [comment]
Please use JIRA to report issues against Keycloak. See keycloak.org/community for more details.
