### ISSUE TITLE
wrong structure in access-token when using a dot in token claim name of group membership mapper

### ISSUE THREAD

**Issue by jlefebvre-vsct** [keycloak/keycloak-community#48]
When using a dot in the token claim name in the group membership mapper type of a client scope, the dot is escaped instead of causing a nested JSON in the token (as specified in the tooltip).
This is not the cas when using other mapper types : a nested JSON is correctly generated.

**Comment by stianst** [comment]
Please use our mailing list for help, and issue tracker in JIRA to report issues. See https://www.keycloak.org/community for more details.
