### ISSUE TITLE
Unable to set timezone in Keycloak 9.x docker container

### ISSUE THREAD

**Issue by aleksandar78** [keycloak/keycloak-community#50]
Hi everyone,

I have a strange problem. After updating keycloak docker version to latest 9.x, a command to set TIMEZONE doesn't work anymore. 
```
docker run -d -e TZ=Europe/Rome jboss/keycloak
```
I found that recent version of keycloak docker image is built on redhat ubi8-minimal which doesn't have tzselect configuration. This could be an explanation.

I don't want to create my one docker image with Keycloak. Official images are fine but without the possibility to change timezone I have time expiration on a token level due to our application Europe/Rome timezone.

Any suggestion is welcome

**Comment by stianst** [comment]
Please use our mailing list for help, and issue tracker in JIRA to report issues. See https://www.keycloak.org/community for more details.
