### ISSUE TITLE
Authentication with keycloak as Identity broker: You are already logged in 

### ISSUE THREAD

**Issue by scabarrus** [keycloak/keycloak-community#53]
Hello everyone,

I'm trying to simulate for my current project an authentication app by two step:
- a keycloak instance configured as identity broker and one simple client in python as oidc client
- a keycloak instance configured as identity provider with previous keycloak (identity broker) as client.

I have configure my authentication flow with capabilities to authenticate with a form and by SAML exchange.

When I try authentication by form it works fine, but when I try with SAML:
- I'm redirected to Keycloak as identity provider (behaviour expected)
- I authenticate with the form
- I 'm redirected to keycloak as identity broker but with message "You are already logged in"
In same page, I have possibility to back to application but I lost authentication token.

I have also try to check in logs what's happen, but no error and information that show me the root cause.
`10:30:44,522 DEBUG [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Executed scheduled task AbstractLastSessionRefreshStoreFactory$$Lambda$1255/0x00000008414a7840
10:30:46,806 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) new JtaTransactionWrapper
10:30:46,806 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) was existing? false
10:30:46,807 DEBUG [org.keycloak.protocol.oidc.utils.RedirectUtils] (default task-51) replacing relative valid redirect with: http://192.168.169.137:5000/*
10:30:46,807 DEBUG [org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint] (default task-51) PKCE non-supporting Client
10:30:46,807 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the requests header
10:30:46,807 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the cookies field
10:30:46,814 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (default task-51) Found AUTH_SESSION_ID cookie with value 399c3cb8-ac4d-4aa8-b703-53c11d0476e0.keycloak-broker-deployment-745c9b949b-64htl
10:30:46,814 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the requests header
10:30:46,814 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the cookies field
10:30:46,815 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (default task-51) Found AUTH_SESSION_ID cookie with value 399c3cb8-ac4d-4aa8-b703-53c11d0476e0.keycloak-broker-deployment-745c9b949b-64htl
10:30:46,816 DEBUG [org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider] (default task-51) getUserSessionWithPredicate(399c3cb8-ac4d-4aa8-b703-53c11d0476e0): remote cache not available
10:30:46,818 DEBUG [org.keycloak.protocol.AuthorizationEndpointBase] (default task-51) Sent request to authz endpoint. We don't have root authentication session with ID '399c3cb8-ac4d-4aa8-b703-53c11d0476e0' but we have userSession.Re-created root authentication session with same ID. Client is: python-client . New authentication session tab ID: M9rBqg_Kcgw
10:30:46,818 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (default task-51) AUTHENTICATE
10:30:46,819 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (default task-51) AUTHENTICATE ONLY
10:30:46,819 DEBUG [org.keycloak.authentication.DefaultAuthenticationFlow] (default task-51) processFlow: browser-websso
10:30:46,819 DEBUG [org.keycloak.authentication.DefaultAuthenticationFlow] (default task-51) check execution: identity-provider-redirector requirement: REQUIRED
10:30:46,819 DEBUG [org.keycloak.authentication.DefaultAuthenticationFlow] (default task-51) authenticator: identity-provider-redirector
10:30:46,819 DEBUG [org.keycloak.authentication.AuthenticationSelectionResolver] (default task-51) Selections when trying execution 'identity-provider-redirector' : [ authSelection - identity-provider-redirector]
10:30:46,819 DEBUG [org.keycloak.authentication.DefaultAuthenticationFlow] (default task-51) invoke authenticator.authenticate: identity-provider-redirector
10:30:46,819 DEBUG [org.keycloak.authentication.authenticators.browser.IdentityProviderAuthenticator] (default task-51) Redirecting to WebSSO
10:30:46,819 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) JtaTransactionWrapper  commit
10:30:46,820 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) JtaTransactionWrapper end
10:30:46,824 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) new JtaTransactionWrapper
10:30:46,824 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) was existing? false
10:30:46,825 DEBUG [org.keycloak.services.resources.IdentityBrokerService] (default task-51) Sending authentication request to identity provider [WebSSO].
10:30:46,825 DEBUG [org.keycloak.services.resources.SessionCodeChecks] (default task-51) Will use client 'python-client' in back-to-application link
10:30:46,825 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the requests header
10:30:46,826 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the cookies field
10:30:46,826 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (default task-51) Found AUTH_SESSION_ID cookie with value 399c3cb8-ac4d-4aa8-b703-53c11d0476e0.keycloak-broker-deployment-745c9b949b-64htl
10:30:46,826 DEBUG [org.keycloak.services.resources.IdentityBrokerService] (default task-51) Authorization code is valid.
10:30:46,827 DEBUG [org.keycloak.saml.common] (default task-51) org.keycloak.saml.processing.core.saml.v2.util.XMLTimeUtil issueInstant: 2020-03-21T10:30:46.827Z
10:30:46,834 DEBUG [org.keycloak.services.resources.IdentityBrokerService] (default task-51) Identity provider [org.keycloak.broker.saml.SAMLIdentityProvider@2e7818dd] is going to send a request [org.jboss.resteasy.specimpl.BuiltResponse@79a424fe].
10:30:46,835 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) JtaTransactionWrapper  commit
10:30:46,835 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) JtaTransactionWrapper end
10:30:49,523 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) new JtaTransactionWrapper
10:30:49,523 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) was existing? false
10:30:49,523 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper  commit
10:30:49,524 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper end
10:30:49,524 DEBUG [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Executed scheduled task AbstractLastSessionRefreshStoreFactory$$Lambda$1255/0x00000008414a7840
10:30:50,358 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) new JtaTransactionWrapper
10:30:50,358 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) was existing? false
10:30:50,360 DEBUG [org.keycloak.saml.SAMLRequestParser] (default task-51) <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="http://192.168.169.129:30800/auth/realms/dev/broker/WebSSO/endpoint" ID="ID_e4fc5820-4d69-422e-95fe-f074e7a8317a" InResponseTo="ID_eb738c3e-c8df-4fde-8467-619e2a2df2ab" IssueInstant="2020-03-21T10:30:50.281Z" Version="2.0"><saml:Issuer>http://192.168.169.129:32439/auth/realms/dev</saml:Issuer><dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"><dsig:SignedInfo><dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><dsig:Reference URI="#ID_e4fc5820-4d69-422e-95fe-f074e7a8317a"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><dsig:DigestValue>yaz1EvX1MpaNHYpcJ9rkPKbyEJRE7ucn7+GrXekDy0U=</dsig:DigestValue></dsig:Reference></dsig:SignedInfo><dsig:SignatureValue>OoeInvB/zmCkjmrVQk5MTmwApf9IEgF4B8lZg2hJJ6KpqsGTt4LGPY4pheoxaaEbShTtrFKnI69fvLeO2CLnIir1ezumQzmXDZo8ChK2lygq7Qcfvmmj0xndGQPwb3Xo6HdYtme40MqNA1qmNn6hhsLkwSALeMbi4vzp3pZ4l8DDDGQQz3V3n+QoqKx8xS3b73myW63YcZC4Dt8Nhwi4YdWyWZC68i37Z6pMVF7+me0N2AVbLktRFiTu333wuOel8nzAtb+NPawpYYrAFvMml+by9+MJBk9yfXiMIPSGOmGwLc/HhVZOy2wkgKb/vazj0zzZCZ9DYvPQVV6ZmjeIsw==</dsig:SignatureValue><dsig:KeyInfo><dsig:KeyName>9UVLstaN9tTkVlfcHkGkEpxg8_OVUNUxQc3ug2B2zGQ</dsig:KeyName><dsig:X509Data><dsig:X509Certificate>MIIClTCCAX0CBgFw+BWb7jANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDDANkZXYwHhcNMjAwMzIwMTMxMzUwWhcNMzAwMzIwMTMxNTMwWjAOMQwwCgYDVQQDDANkZXYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCUbG6fzukxckvi6ugowWAWtdbtnJe1VG/2QZCw2IRJwjYSZ1NhQCoNQoXNQKUgg6JKEm+KdHxWYqef/rYHgrmZVqr2p07OdbxOSWDr6V6TJjybV8huUQH7yNE5kY7UGmAp8K1HSBLpRhWGl0Hj8tcFq8+FPWuy9ItxevTV/XfT7E4iiy+p6s0jUsZHACl5aAGXFo0ODW9+uHOkobCaWg071+xUXwM/7b5tJjCaJbp3LiMkjc92fqwv1qkBhPqtyBKB2JPaddyCInr+cB3hLnw0u4ep+B6wsb4tg6c68cRCXt8rm7pwq+HSE9m+ui6b1xrEI+GLTUNzIyiy6TPIWqjzAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAFgigPFt/gouMi9xWj+HFJYto6skIV122nFiOinTH+4s+Vc9bCdIkIs5R+NVRUNeUN6rSt4p9ZquNO6UgUyd09VN/hCpO5fREECjUYV+la8LLNw6iU8UmDRbXgcbifVmT73EZxBl9es+ipxkAAv1wnlL9FZf3zbPFo/OxDNcgdne1ehwCzTwtbcIFrzs01KqVcuVjVnU7ztXEJomWhMbWy2xTXIVik4jJ1+d3qaUgMqEEFh7S25dLQYqhNI/AmUIx4IwQNhteFj553QcHycMeHz6wlk/XAmxxpawvxs8sN30/4MYxV2a1IW9sNxolUaW5if3Y13H3zWN6uZVCf+ZkPk=</dsig:X509Certificate></dsig:X509Data><dsig:KeyValue><dsig:RSAKeyValue><dsig:Modulus>lGxun87pMXJL4uroKMFgFrXW7ZyXtVRv9kGQsNiEScI2EmdTYUAqDUKFzUClIIOiShJvinR8VmKnn/62B4K5mVaq9qdOznW8Tklg6+lekyY8m1fIblEB+8jROZGO1BpgKfCtR0gS6UYVhpdB4/LXBavPhT1rsvSLcXr01f130+xOIosvqerNI1LGRwApeWgBlxaNDg1vfrhzpKGwmloNO9fsVF8DP+2+bSYwmiW6dy4jJI3Pdn6sL9apAYT6rcgSgdiT2nXcgiJ6/nAd4S58NLuHqfgesLG+LYOnOvHEQl7fK5u6cKvh0hPZvroum9caxCPhi01DcyMosukzyFqo8w==</dsig:Modulus><dsig:Exponent>AQAB</dsig:Exponent></dsig:RSAKeyValue></dsig:KeyValue></dsig:KeyInfo></dsig:Signature><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="ID_d3ae2fff-4883-4f22-85ba-77c0b2a6a8fc" IssueInstant="2020-03-21T10:30:50.281Z" Version="2.0"><saml:Issuer>http://192.168.169.129:32439/auth/realms/dev</saml:Issuer><saml:Subject><saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">G-6c669c76-4d5a-42dc-9e1b-722ee61c8a93</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData InResponseTo="ID_eb738c3e-c8df-4fde-8467-619e2a2df2ab" NotOnOrAfter="2020-03-21T10:31:48.281Z" Recipient="http://192.168.169.129:30800/auth/realms/dev/broker/WebSSO/endpoint"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="2020-03-21T10:30:48.281Z" NotOnOrAfter="2020-03-21T10:31:48.281Z"><saml:AudienceRestriction><saml:Audience>http://192.168.169.129:30800/auth/realms/dev</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant="2020-03-21T10:30:50.281Z" SessionIndex="399c3cb8-ac4d-4aa8-b703-53c11d0476e0::4e2be45f-1614-4fc8-aa82-0ce35acf3c14" SessionNotOnOrAfter="2020-03-21T11:30:50.281Z"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement><saml:AttributeStatement><saml:Attribute FriendlyName="email" Name="urn:oid:1.2.840.113549.1.9.1" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">user1@domain.com</saml:AttributeValue></saml:Attribute><saml:Attribute FriendlyName="givenName" Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">user</saml:AttributeValue></saml:Attribute><saml:Attribute FriendlyName="surname" Name="urn:oid:2.5.4.4" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">1</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">offline_access</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-account</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">simple-user</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">uma_authorization</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-profile</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-account-links</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">simple-user</saml:AttributeValue></saml:Attribute></saml:AttributeStatement></saml:Assertion></samlp:Response>
10:30:50,362 DEBUG [org.keycloak.saml.common] (default task-51) org.keycloak.saml.processing.core.saml.v2.util.XMLTimeUtil issueInstant: 2020-03-21T10:30:50.362Z
10:30:50,362 DEBUG [org.keycloak.saml.validators.ConditionsValidator] (default task-51) Evaluating Conditions of Assertion ID_d3ae2fff-4883-4f22-85ba-77c0b2a6a8fc. notBefore=2020-03-21T10:30:48.281Z, notOnOrAfter=2020-03-21T10:31:48.281Z, updatedNotBefore: 2020-03-21T10:30:48.281Z, updatedOnOrAfter=2020-03-21T10:31:48.281Z, now: 2020-03-21T10:30:50.362Z
10:30:50,362 DEBUG [org.keycloak.saml.validators.ConditionsValidator] (default task-51) Assertion ID_d3ae2fff-4883-4f22-85ba-77c0b2a6a8fc validity is VALID
10:30:50,362 DEBUG [org.keycloak.services.resources.SessionCodeChecks] (default task-51) Will use client 'python-client' in back-to-application link
10:30:50,363 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the requests header
10:30:50,363 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the cookies field
10:30:50,363 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (default task-51) Found AUTH_SESSION_ID cookie with value 399c3cb8-ac4d-4aa8-b703-53c11d0476e0.keycloak-broker-deployment-745c9b949b-64htl
10:30:50,365 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the requests header
10:30:50,365 DEBUG [org.keycloak.services.util.CookieHelper] (default task-51) {1} cookie found in the cookies field
10:30:50,365 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager] (default task-51) Found AUTH_SESSION_ID cookie with value 399c3cb8-ac4d-4aa8-b703-53c11d0476e0.keycloak-broker-deployment-745c9b949b-64htl
10:30:50,369 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) JtaTransactionWrapper  commit
10:30:50,369 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-51) JtaTransactionWrapper end
10:30:54,523 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) new JtaTransactionWrapper
10:30:54,523 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) was existing? false
10:30:54,524 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper  commit
10:30:54,524 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper end
10:30:54,524 DEBUG [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Executed scheduled task AbstractLastSessionRefreshStoreFactory$$Lambda$1255/0x00000008414a7840
10:30:59,524 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) new JtaTransactionWrapper
10:30:59,525 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) was existing? false
10:30:59,525 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper  commit
10:30:59,525 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper end
10:30:59,525 DEBUG [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Executed scheduled task AbstractLastSessionRefreshStoreFactory$$Lambda$1255/0x00000008414a7840
`
If anyone has an idea, that will be great for me.
Best regards,

**Comment by stianst** [comment]
See https://www.keycloak.org/community for details on how to ask for help, and report issues
