### ISSUE TITLE
Authentication query parameters are not propagated

### ISSUE THREAD

**Issue by daniel-esq** [keycloak/keycloak-community#98]
I am trying to use **kc_idp_hint** query parameter to skip the login page as the documentation suggests using _spring-boot_.

I was first trying with version **6.0.1** where I got stuck by the following exception:
`ERROR o.k.a.OAuthRequestAuthenticator – failed verification of token: Invalid token issuer. Expected 'http://demo-redhat-sso-stub-default-minikube.service.np.com/auth/realms/demo?kc_idp_hint=stackoverflow', but was 'http://demo-redhat-sso-stub-default-minikube.service.np.com/auth/realms/demo'`

I moved then to version **9.0.3** where I got stuck on:
`DEBUG o.k.adapters.KeycloakDeployment – Resolving URLs from http://demo-redhat-sso-stub-default-minikube.service.np.com/auth/realms/demo/.well-known/openid-configuration?kc_idp_hint=stackoverflow
INFO  o.k.adapters.KeycloakDeployment – Loaded URLs from http://demo-redhat-sso-stub-default-minikube.service.np.com/auth/realms/demo/.well-known/openid-configuration?kc_idp_hint=stackoverflow
DEBUG o.k.a.s.f.KeycloakAuthenticationProcessingFilter – Auth outcome: NOT_ATTEMPTED
DEBUG o.k.a.OAuthRequestAuthenticator – Sending redirect to login page: http://demo-redhat-sso-stub-default-minikube.service.np.com/auth/realms/demo/protocol/openid-connect/auth?response_type=code&client_id=hops-ui&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fsso%2Flogin&state=4d4a5bea-2231-462d-9b4d-a97c13e9adfd&login=true&scope=openid
`
The **kc_idp_hint** is not present in the last call that is meant to skip the SSO Login page. For some reason the **OAuthRequestAuthenticator.getRedirectUri** method is not able to fetch it.

Tech stack:
- java 8
- spring 2.2.0.RELEASE
- redhat-sso-7.2
   - client and identity provider correctly configured as the login flow works as expected

Last thing, I'm trying to pass the parameter in the auth-url:
`keycloak.auth-server-url=http://demo-redhat-sso-stub-default-minikube.service.np.com/auth?kc_idp_hint=stackoverflow`

**Comment by stianst** [comment]
See https://www.keycloak.org/community for details on how to ask for help and report issues
